- CHANGELOG.md
- internal/meta/version.go
- internal/table/scanner/scanner.go
I have type:
```golang
type UUID struct {
uuid.UUID
}
func (d *UUID) UnmarshalYDB(v types.RawValue) error {
...
}
```
It has explicit implementation for types.Scanner and implicit sql.Scanner (from uuid.UUID type).
When I do res.ScanWithDefaults for my UUID - it try use sql.Scanner for scan nil value and throw error: "uuid: cannot convert <nil> to UUID".
In this PR I set priority of special YDB scanner implementation higher then more generic sql scanner.
If type implement both sql.Scanner and types.Scanner (ydb) interfaces - scanner prefer sql.Scanner implementation.
If type implement both sql.Scanner and types.Scanner (ydb) interfaces - scanner …
> Prefer YDB scanner interface

- .gitignore
- CHANGELOG.md
- connection.go
- discovery/config/config.go
- internal/cluster/cluster.go
- internal/conn/conn.go
- internal/conn/pool.go
- internal/db/database.go
- internal/discovery/discovery.go
- options.go
- test/discovery_test.go
- with.go
Create new meta for gRPC call exclusively inside `internal/conn` package.
Currently there are several places where new outgoing meta is created.
Create new meta for gRPC call exclusively inside `internal/conn` package.
> move meta call to conn exclusively

- CHANGELOG.md
- config/config.go
- connection.go
- internal/cluster/cluster.go
- internal/conn/conn.go
- internal/db/connection.go
- internal/db/database.go
- internal/discovery/discovery.go
- test/connection_test.go
- with.go
* Added `config.SharedPool()` setting and `config.WithSharedPool()` option
* Added management of shared pool flag on change dial timeout and credentials
* Removed explicit checks of conditions for use (or not) shared pool in `ydb.With()`
* Renamed `internal/db` interfaces
* Changed signature of `conn.Conn.Release` (added error as result)
-
-
-
> shared pool management with config

- .github/scripts/wait-ydb-container.sh
- .github/workflows/tests.yml
Start table tests right repository checkout
Wait while ydb container complete start and ydb service available. It prevent race condition between start test and background starting of ydb container.
> wait ydb container ready before table tests

- CHANGELOG.md
- config/config.go
- internal/dsn/dsn.go
- internal/dsn/dsn_test.go
- options.go
- sugar/certificates.go
The SDK's default tls.Config contains root CA. User may appends custom certificates to defaults TLS config, redefine min TLS version and change InsecureSkipVerify flag. 
Also internal config field secure is an ambigious with TLS config. Always true secure flag indirectly redefines tls config with default TLS, false secure flag skips TLS config to nil.
PR's contains changes for using user-defined tls.Config explicitly and deprecates other options about TLS config.
CHANGELOG:
* Added `WithTLSConfig` option for redefine TLS config
* Marked as deprecated options `WithSecure`, `WithInSecure`, `WithMinTLSVersion`, `WithTLSSInsecureSkipVerify`, `WithCertificate`, `WithCertificatesFromFile, …
> define tls.Config explicitly instead redefine default TLS config options 

- CHANGELOG.md
- config/config.go
- internal/config/config.go
- internal/coordination/client.go
- internal/lazy/coordiantion.go
- internal/lazy/ratelimiter.go
- internal/lazy/scheme.go
- internal/lazy/scripting.go
- internal/lazy/table.go
- internal/ratelimiter/ratelimiter.go
- internal/scheme/scheme.go
- internal/scripting/scripting.go
- internal/table/client.go
- internal/table/client_test.go
- internal/table/session_test.go
* Fixed re-opening case after close lazy-initialized clients
* Removed dependency of call context for initializing lazy table client
-
-
-
> Fix bug with reopening lazy table client on call after Close()

- CHANGELOG.md
- internal/balancer/mock/conn.go
- internal/cluster/cluster.go
- internal/conn/conn.go
- internal/conn/grpc_client_stream.go
- internal/conn/pool.go
- internal/discovery/discovery.go
- internal/xerrors/transport.go
- table/table_test.go
* Removed `internal/conn/conn.streamUsages` and `internal/conn/conn.usages` (`internal/conn.conn` always touching last usage timestamp on API calls)
* Added `config.AutoReconnect()` flag for auto-reconnecting broken conns
Issue Number: #232 #231 #219 
-
-
-
> Removed internal counters of conn.Conn + disable auto-reconnection of broken conns

- CHANGELOG.md
- internal/repeater/repeater.go
Initial force timeout 500 seconds (in fact - deny second force discovery)
Initial force timeout 500 milliseconds (0.5 second)
> Fixed repeater force initial timeout

- CHANGELOG.md
- internal/value/value.go
- table/types/value.go
Add some enhancements to struct value contruction.
Now every field represented as closure and its apply leads to strange stack calls and slices growth.
- Add method to set slices size at constructor call
- Make StructValueOption interface with struct implementation to not store closures in stack
> enhance struct value construction

- CHANGELOG.md
- internal/table/scanner/scan_raw.go
- internal/table/scanner/scanner.go
- internal/table/scanner/scanner_test.go
- internal/timeutil/time.go
- internal/value/value.go
- table/table_regress_test.go
- table/types/value.go
- table/types/value_test.go
> Interval <-> time.Duration fix

- .github/workflows/breaking.yml
gorelease installed with go 1.17, but need go 1.18 for compile.
We not need special go version for the util, use latest.
> Install gorelease util with latest go

- CHANGELOG.md
- internal/conn/grpc_client_stream.go
- internal/repeater/repeater.go
- internal/table/session.go
- internal/xcontext/cancel_with_error.go
- internal/xcontext/cancel_with_error_test.go
Context always cancel with context.Canceled error and not show source/reason of cancelation.
Add xcontext.WithErrCancel function - for cancel context with reason.
> context cancel with reason

- CHANGELOG.md
- internal/grpcwrapper/rawtopic/rawtopicreader/messages.go
- internal/grpcwrapper/rawtopic/rawtopicreader/rawtopicreader.go
- internal/topic/topicreaderinternal/batcher.go
- internal/topic/topicreaderinternal/batcher_test.go
- internal/topic/topicreaderinternal/stream_reader_impl.go
- internal/topic/topicreaderinternal/stream_reader_impl_test.go
- internal/xtest/manytimes.go
- internal/xtest/waiters.go
- topic/client_e2e_test.go
- topic/reader_e2e_test.go
- topic/topicoptions/topicoptions_create.go
1. Close with error if receive signal about stop partition.
```
Read stream error: ydb: send unexpected message type: *rawtopicreader.StopPartitionSessionResponse at `github.com/ydb-platform/ydb-go-sdk/v3/internal/grpcwrapper/rawtopic/rawtopicreader.StreamReader.Send(rawtopicreader.go:140)
```
2. Deadlock if same time add raw messages to internal topic batcher and read from it.
1. Handle stop partition fine
2. Work good
> Implement send stop partition message

- CHANGELOG.md
- README.md
- connection.go
- discovery/discovery_e2e_test.go
- internal/logger/log.go
- internal/logger/options.go
- logger_options.go
* Changed default behaviour of internal logger to without coloring
* Fixed coloring (to true) with environment variable `YDB_LOG_SEVERITY_LEVEL`
-
-
-
> * Removed support of `YDB_LOG_NO_COLOR` environment variable

- CHANGELOG.md
- internal/table/client.go
- internal/table/params.go
- internal/table/session.go
- internal/table/transaction.go
- internal/xsql/badconn/badconn_go1.18.go
- internal/xsql/conn.go
- internal/xsql/errors.go
- internal/xsql/isolation/isolation.go
- internal/xsql/isolation/isolation_test.go
- internal/xsql/rows.go
- internal/xsql/tx.go
- internal/xsql/xsql.go
- log/table.go
- retry/sql.go
- retry/sql_test.go
- sql_e2e_test.go
- sugar/params.go
- trace/sql.go
- trace/sql_gtrace.go
- trace/table.go
- trace/table_gtrace.go
* Moved implementation `sugar.GenerateDeclareSection` to `internal/table`
* Added transaction trace callbacks and internal logging with them
* Stored context from `BeginTx` to `internal/xsql` transaction
* Added automatically generated declare section to query text in `database/sql` usage
* Removed supports `sql.LevelSerializable`
* Added `retry.Do` helper for retry custom lambda with `database/sql` without transactions
* Removed `retry.WithTxOptions` option (only default isolation supports)
-
-
-
> * Added some description to error message from table pool get

- CHANGELOG.md
- internal/topic/topicreaderinternal/stream_reconnector.go
- internal/topic/topicreaderinternal/stream_reconnector_test.go
- topic/reader_e2e_test.go
nil panic if reconnect to ydb failed
return reconnect error instead of panic
> fix panic on nil stream in connect failed

- CHANGELOG.md
- internal/grpcwrapper/rawtopic/alter_topic.go
- topic/topicoptions/topicoptions_alter.go
Always sent setSupportedCodecs field for alter topic request, even if them not set from customer (sent empty list)
Sent setSupportedCodecs only if them explicit set.
> Stop sent empty support codec if customer not set it

- internal/topic/topicreaderinternal/stream_reader_impl_test.go
- internal/xtest/manytimes.go
Exit from test right after check errors
Explicit wait for stop partition response sent.
> Fix flaky test TestStreamReaderImpl_OnPartitionCloseHandle/TraceGracefulTrue

- CHANGELOG.md
- coordination/coordination.go
- discovery/discovery.go
- internal/balancer/balancer.go
- internal/balancer/connections_state.go
- internal/balancer/ctx.go
- internal/mock/conn.go
- internal/table/client.go
- internal/table/client_test.go
- internal/table/session.go
- ratelimiter/ratelimiter.go
- scheme/scheme.go
- scripting/scripting.go
- table/table.go
- testutil/driver.go
- topic/client.go
* Added to balancer notifying mechanism for listening in table client event about removing some nodes and closing sessions on them 
* Removed from public client interfaces `closer.Closer` (for exclude undefined behaviour on client-side)
Issue Number: #372 
-
-
-
> add listening discovery results for closing sessions on removed nodes early

- internal/xtest/test_condition.go
- table/table_e2e_test.go
Direct check os env var for allow/deny run special tests
use spec function for check allow/skip test flag
> use function to check os env flag before test start

- CHANGELOG.md
- connection.go
- internal/xsql/conn.go
- internal/xsql/convert.go
- sql_e2e_test.go
- sugar/params_go1.18.go
- table/table.go
* Added `sugar.ToYdbParam(sql.NamedArg)` helper for converting `sql.NamedArg` to `table.ParameterOption`
* Changed type `table.ParameterOption` for getting name and value from `table.ParameterOption` instance
-
-
-
> * Fixed bug in `db.Scripting()` queries (not checked operation results)

- CHANGELOG.md
- go.mod
- go.sum
- internal/grpcwrapper/rawtopic/rawtopicwriter/streamwriter.go
- internal/grpcwrapper/rawtopic/rawtopicwriter/streamwriter_test.go
- internal/topic/topicwriterinternal/message.go
- internal/topic/topicwriterinternal/queue.go
- internal/topic/topicwriterinternal/queue_test.go
- internal/topic/topicwriterinternal/writer_options.go
- internal/topic/topicwriterinternal/writer_reconnector.go
- internal/topic/topicwriterinternal/writer_reconnector_test.go
- topic/topicoptions/topicoptions_writer.go
- topic/topicwriter/topicwriter.go
No limit - add new messages to queue while it can stored in process memory.
If queue is full - sender will pause and wait free space in buffer.
> Add queue len limit for send messages to topic

- internal/operation/status.go
bitmask not used not and no reason for use
Operation status as difficult bitmask formula
Status as usual iota-based enum
> change operation status from bitmask to enum.

- internal/topic/topicreaderinternal/batcher.go
- internal/topic/topicreaderinternal/batcher_test.go
- internal/topic/topicreaderinternal/stream_reader_impl_test.go
exit without wait data request message
explicit wait data request message
> more stable TestTopicStreamReaderImpl_CommitStolen/SimpleCommit test

- CHANGELOG.md
- internal/topic/topicclientinternal/client.go
- internal/topic/topicwriterinternal/writer.go
- internal/topic/topicwriterinternal/writer_reconnector.go
Fast error on create writer
Error while connect to a server and return error on write message.
> fast error if producer_id not equal to message group id

- CHANGELOG.md
- internal/table/session.go
- table/options/models.go
- [ x] Feature
IndexDescription does not contain DataColumns attribute, although it is available in protobuf message
DataColumns are set to IndexDescription from protobuf messate
-
-
-
> Add DataColumns to IndexDescription

- CHANGELOG.md
- internal/topic/topicreaderinternal/committer.go
- internal/topic/topicreaderinternal/committer_test.go
- internal/topic/topicreaderinternal/partition_session.go
- internal/topic/topicreaderinternal/reader.go
- internal/topic/topicreaderinternal/reader_test.go
- internal/topic/topicreaderinternal/stream_reader_impl.go
- internal/topic/topicreaderinternal/stream_reader_impl_test.go
- internal/topic/topicreaderinternal/stream_reconnector.go
- internal/topic/topicreaderinternal/stream_reconnector_test.go
- topic/topicreader/errors.go
- topic/topicreader/reader.go
All commits from unknows session threaded as error with commit from other reader
track session's reader by reader id and unknown session for right reader thread as commit to expired session
> separate commit for expired session and other reader

- .github/workflows/tests.yml
- internal/xtest/waiters.go
- topic/client_e2e_test.go
- topic/topic_read_writer_e2e_test.go
- topic/topic_stress_test.go
Add short (about 10 seconds) concurency test for topic reader/writer.
> Add short stress test of topic reader-writer

- internal/topic/topicreaderinternal/stream_reader_impl_test.go
Common env require send init request package by test client.
But some times test can finished before initial size request sent.
send initial request is optional.
Common env not test the initial state - it is stub only for common client work good.
> fix flack send initial size

- CHANGELOG.md
- internal/topic/retriable_error.go
- internal/topic/retriable_error_test.go
Call customer callback for retry policy for all error check, including check nil errors.
Not call callback if err == nil
> Doesn't call checkerr callback with nil error

- internal/background/worker_test.go
- internal/xtest/context.go
https://github.com/ydb-platform/ydb-go-sdk/issues/578
1. Fixed number of parallels starters (workload) = 10
2. Wait close in separate goroutine
* Limit parallel by GOMAXPROCS (current  2 or 3 for [github runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners))
* Use context with timeout in main goroutine
> fix flaky test TestWorkerConcurrentStartAndClose

- CHANGELOG.md
- internal/topic/topicwriterinternal/writer_reconnector.go
- tests/integration/topic_read_writer_test.go
Deny start writer with partition number instead of message group id with error "ydb: producer id not equal to message group id, use option WithMessageGroupID(producerID) for create writer"
Allow set partition number to writer
> allow set force partition for topic writer

- CHANGELOG.md
- internal/logger/log.go
- internal/logger/options.go
- logger_options.go
- tests/integration/connection_test.go
- tests/integration/discovery_test.go
- tests/integration/ratelimiter_test.go
- tests/integration/scripting_test.go
- tests/integration/table_bulk_upsert_test.go
- tests/integration/table_create_table_description_test.go
- tests/integration/table_long_stream_test.go
- tests/integration/table_multiple_result_sets_test.go
- tests/integration/table_test.go
- tests/integration/topic_read_writer_test.go
* Marked as deprecated `ydb.WithErrWriter(w)` and `ydb.WithOutWriter(w)` logger options
* Added `ydb.WithWriter(w)` logger option
-
-
-
> * Changed default output stream of internal logger to `io.Stderr`

- CHANGELOG.md
- internal/topic/topicclientinternal/client.go
- internal/topic/topicwriterinternal/writer_options.go
- internal/topic/topicwriterinternal/writer_reconnector.go
- tests/integration/topic_read_writer_test.go
- tests/integration/topic_stress_test.go
- topic/client.go
- topic/topicoptions/topicoptions_writer.go
- topic/topicoptions/topicoptions_writer_example_test.go
- topic/topicwriter/topicwriter_test.go
producer id must be as first parameter to start topic writer
WithMessageGroupID option id must be explicit set to equals with producer id
No need explicit set producer id
Option WithMessageGroupID was removed because difference ProducerID and MessageGroupID are not supported now.
Explicit set producerID available with option WithProducerID
> topic api changes

- CHANGELOG.md
- internal/value/time.go
- internal/value/time_test.go
- tests/integration/table_tz_timestamp_test.go
> * Fixed bug with parsing of `TzTimestamp` without microseconds

- CHANGELOG.md
- internal/topic/topicreaderinternal/commit_range.go
- internal/topic/topicreaderinternal/committer.go
- log/topic.go
- trace/topic.go
- trace/topic_gtrace.go
Start and end offset omitted in logs
Issue Number: issue-826
- Add new fields for each commit message (topic, partition, start offset, end offset)
- Log each commit range in message separetly (for consistency with TopicReaderCommitStartInfo and easier log investigation)
> issue-826: write to log offset ranges for OnReaderSendCommitMessage

- CHANGELOG.md
- table/types/value.go
Remove extra allocations in `types.TupleValue`, `types.ListValue` and `types.SetValue`
> Remove extra allocations in types package

- CHANGELOG.md
- metrics/README.md
- metrics/config.go
- metrics/coordination.go
- metrics/counter.go
- metrics/discovery.go
- metrics/driver.go
- metrics/error.go
- metrics/example_test.go
- metrics/gauge.go
- metrics/histogram.go
- metrics/node_id.go
- metrics/ratelimiter.go
- metrics/registry.go
- metrics/retry.go
- metrics/scheme.go
- metrics/scripting.go
- metrics/sql.go
- metrics/table.go
- metrics/timer.go
- metrics/traces.go
- table/table.go
- tests/integration/database_sql_test.go
- tests/integration/metrics_registry_go1.18_test.go
- tests/integration/metrics_registry_test.go
- tests/integration/table_test.go
- trace/table.go
* Refactored default logger format
* Refactored `internal/conn.coonError` format
* Fixed data race on `internal/conn.conn.cc` access
* Added repeater event type to wake-up func context
* Fixed redundant trace call for finished `database/sql` transactions
Issue Number: #477
```
[2023-10-03 18:00:58] final registry state:
- gauges:
- ydb.driver.balancer.endpoints{az=VLA,local_dc=true} = 8.000000
- ydb.table.pool.limit{} = 50.000000
- ydb.table.pool.size{} = 0.000000
- ydb.table.pool.wait{} = 0.000000
- ydb.table.sessions{node_id=50005} = 0.000000
- ydb.table.sessions{node_id=50008} = 0.000000
- ydb.table.sessions{node_id=50006} = 0.000000
- …
```
> * Added package `metrics` with SDK metrics

- CHANGELOG.md
- internal/backoff/backoff.go
- internal/repeater/repeater.go
- internal/topic/topicreaderinternal/stream_reconnector.go
- internal/wait/wait.go
- internal/xsql/errors.go
> Removed `backoff.Backoff.Wait` interface method for exclude resource leak with bug-provoked usage of `time.After`

- CHANGELOG.md
- internal/table/scanner/scanner.go
- tests/integration/table_regress_test.go
```
panic: runtime error: index out of range [-128]
```
when try to unwrap values when scan wide result with custom unmarhsalers.
Work fine
> fix unwrap raw values in wide results

- CHANGELOG.md
- internal/allocator/allocator.go
- internal/allocator/allocator_go1.18.go
- internal/bind/auto_declare.go
- internal/bind/bind.go
- internal/bind/numeric_args.go
- internal/bind/positional_args.go
- internal/bind/table_path_prefix.go
- internal/credentials/access_error.go
- internal/credentials/access_token.go
- internal/credentials/anonymous.go
- internal/credentials/static.go
- internal/stack/record.go
- internal/table/scanner/scanner.go
- internal/value/type.go
- internal/value/value.go
- internal/xerrors/issues.go
- internal/xerrors/join.go
- internal/xerrors/operation.go
- internal/xstring/buffer.go
- internal/xstring/buffer_test.go
- log/field.go
- log/logger.go
- metrics/error_brief.go
- table/table.go
```
BenchmarkBufferWithPool-8      	51107196	        22.97 ns/op	       0 B/op	       0 allocs/op
BenchmarkBufferWithoutPool-8   	27986596	        46.01 ns/op	      64 B/op	       1 allocs/op
```
-
-
-
> * Moved `internal/allocator.Buffers` to package `internal/xstring`

- CHANGELOG.md
- config/config.go
- connection.go
- internal/balancer/balancer.go
- internal/config/config.go
- internal/coordination/client.go
- internal/ratelimiter/client.go
- internal/scheme/client.go
- internal/scripting/client.go
- internal/table/client.go
- internal/table/retry.go
- internal/topic/topicclientinternal/client.go
- internal/xsql/connector.go
- metrics/retry.go
- metrics/traces.go
- options.go
- retry/retry.go
- retry/retry_test.go
- retry/sql.go
- retry/sql_test.go
- sql.go
- tests/integration/with_trace_retry_test.go
- tests/slo/database/sql/storage.go
- tests/slo/gorm/storage.go
- tests/slo/xorm/storage.go
> * Added `ydb.WithTraceRetry` option

- CHANGELOG.md
- internal/table/retry.go
- log/retry.go
- log/table.go
- metrics/table.go
- retry/retry.go
- retry/sql.go
- table/table.go
- tests/integration/with_trace_retry_test.go
- trace/retry.go
- trace/retry_gtrace.go
- trace/table.go
- trace/table_gtrace.go
> * Renamed `{retry,table}.WithID` option to `{retry,table}.WithLabel`

- CHANGELOG.md
- metrics/driver.go
- metrics/retry.go
- metrics/sql.go
- metrics/table.go
- retry/retry.go
> * Refactored traces and metrics

- CHANGELOG.md
- internal/xerrors/join.go
- internal/xerrors/join_test.go
To support logic of processing inner errors
It is unable to enumerate inner errors without reflection.
You can cast `joinError` to standard `interface {Unwrap()[] error}` And work with inner errors.
> Allow to unwrap joined errors

- internal/xsql/conn.go
- internal/xsql/connector.go
- internal/xsql/stmt.go
- internal/xsql/tx.go
- internal/xsql/tx_fake.go
- trace/sql.go
- trace/sql_gtrace.go
> Added function id into database/sql traces (start info's) + Fix of breaking changes

- internal/balancer/balancer.go
- internal/balancer/balancer_test.go
- internal/balancer/local_dc_test.go
- log/driver.go
- trace/driver.go
- trace/driver_gtrace.go
> added `Added` and `Dropped` fields into balancer update done info

- .github/workflows/slo.yml
> allow to fail SLO tests

- CHANGELOG.md
- driver.go
context for option has same lifetime as connection token
context for options has same lifetime as driver
Close: #898
> separate lifetime for option context from connection context

- .golangci.yml
- connection.go
- driver.go
- errors.go
- example_test.go
- options.go
- query_bind_test.go
- sql.go
- sql_unwrap.go
- sql_unwrap_go1.18.go
- with.go
- with_test.go
> Change golangci to enable all

- CHANGELOG.md
- metrics/error_brief.go
- metrics/retry.go
- metrics/sql.go
- metrics/table.go
There are not enough metrics and statuses
- added callbacks in database.sql metrics
- added TLI error recognition
> extend metric callbacks

- CHANGELOG.md
- examples/go.mod
- examples/go.sum
- go.mod
- go.sum
- internal/grpcwrapper/rawtopic/rawtopiccommon/message_metadata.go
- internal/grpcwrapper/rawtopic/rawtopicreader/messages.go
- internal/grpcwrapper/rawtopic/rawtopicwriter/messages.go
- internal/topic/topicreaderinternal/batch.go
- internal/topic/topicreaderinternal/message.go
- internal/topic/topicreaderinternal/stream_reader_impl_test.go
- internal/topic/topicwriterinternal/encoders.go
- internal/topic/topicwriterinternal/encoders_test.go
- internal/topic/topicwriterinternal/message.go
- internal/topic/topicwriterinternal/writer.go
- internal/topic/topicwriterinternal/writer_reconnector.go
- internal/topic/topicwriterinternal/writer_reconnector_test.go
- internal/topic/topicwriterinternal/writer_stream_interface.go
- internal/topic/topicwriterinternal/writer_stream_interface_mock_test.go
- internal/topic/topicwriterinternal/writer_test.go
- internal/xbytes/clone.go
- internal/xbytes/clone_go1.20.go
- log/logger_test.go
- tests/integration/helpers_test.go
- tests/integration/topic_read_writer_test.go
- tests/slo/go.mod
- tests/slo/go.sum
- topic/topicwriter/topicwriter.go
Close: https://github.com/ydb-platform/ydb-go-sdk/issues/904
> add metadata to messages

- CHANGELOG.md
- driver.go
Implement String() for Driver
https://github.com/ydb-platform/ydb-go-sdk/issues/549
Issue Number: https://github.com/ydb-platform/ydb-go-sdk/issues/549
`Driver` that implements `Connection` interface doesn't implement `String` interface
`Driver` implements `String` interface and can be used for debugging
> dev: Implement String() for Connection and/or configs for print debug info on fails

- CHANGELOG.md
- config/defaults.go
- driver.go
- driver_string.go
- driver_string_test.go
- internal/credentials/access_error_test.go
- internal/credentials/access_token.go
- internal/credentials/anonymous.go
- internal/credentials/credentials_test.go
- internal/credentials/static.go
> Driver string

- .github/workflows/lint.yml
- .golangci.yml
> Revert golangci config

- .golangci.yml
- sugar/params_go1.18.go
- sugar/params_go1.18_test.go
> asasalint enable

- .golangci.yml
- examples/pagination/cities.go
> nakedret enabled

- .golangci.yml
- examples/serverless/url_shortener/service.go
> promlinter enabled

- .golangci.yml
- CHANGELOG.md
- internal/conn/error_test.go
- internal/meta/trace_id_test.go
- internal/table/client_test.go
- internal/table/scanner/result_test.go
- internal/topic/topicreaderinternal/reader_test.go
- internal/topic/topicwriterinternal/writer_reconnector_test.go
- internal/xerrors/transport_test.go
- internal/xsync/event_broadcast_test.go
- log/logger_test.go
- table/options/models_test.go
- table/options/options_test.go
Fixed testifylint warnings.
testifylint doesn't show warnings.
Issue Number: #970
> enabled testifylint

- CHANGELOG.md
- internal/topic/topicwriterinternal/writer_reconnector.go
- internal/topic/topicwriterinternal/writer_reconnector_test.go
- internal/topic/topicwriterinternal/writer_single_stream.go
- internal/topic/topicwriterinternal/writer_single_stream_test.go
- tests/integration/topic_regression_test.go
Closed: https://github.com/ydb-platform/ydb-go-sdk/issues/1011
> Fixed init info in topic writer, when autoseq num turned off.

- tests/integration/topic_read_writer_test.go
Tests TestUpdateToken and TestManyConcurentReadersWriters was disabled for wait fix issues. Issues fixed already.
> Enable temporary disabled tests

- internal/topic/retriable_error.go
- internal/topic/retriable_error_test.go
- internal/topic/topicwriterinternal/writer_reconnector.go
- internal/topic/topicwriterinternal/writer_reconnector_test.go
Hello! 
I've created topic writer with `StartTimeout` 30 seconds and Default or Retry `RetryPolicy`.
Then with ip6tables I've blocked the YDB port to get transport error.
The retries are expected to stop after 30 seconds, but this does not happened. 
The reason why this is happened is `connectionTimeout*resetAttemptEmpiricalCoefficient` overflow. 
If `connectionTimeout` is `time.Duration(math.MaxInt64)` (that is always true, since we do not have options to set `connectionTimeout`), then its multiplication to empirical coefficient (=10) gives negative value (see playground https://goplay.space/#qlIeS6o3PCz). 
As a result, function `CheckResetReconnectionCounters` always returns true. Since …
> Fix topic writer infinite reconnections

- CHANGELOG.md
- tests/integration/helpers_test.go
Hangup at TestDatabaseSqlGetColumnType test by cycle dependency at fixenv wrapper.
Use fixenv cache directly, without wrapping
> Fixed fixenv usage

- .github/workflows/publish.yml
For prevent situation when tag point to commit, which doesn't exist in main branch.
push tags, then push branch
push branch then push tags
It prevent situation, when exists tag for commit without branch (if push to branch fail)
> Push to main branch before create tag.

- CHANGELOG.md
- internal/grpcwrapper/rawtopic/rawtopicreader/rawtopicreader.go
Unhadnled EOF error converted to transport error with gRPC code `Unknown`.
Issue Number: SLYDB-894
EOF handled correctly.
> Handle EOF error when reading stream.

- CHANGELOG.md
- internal/meta/context.go
- internal/meta/context_test.go
- internal/meta/headers.go
- internal/meta/meta.go
- internal/meta/test/meta_test.go
> * Added client pid to each gRPC requests to YDB over header `x-ydb-client-pid`

- CHANGELOG.md
- internal/params/parameters.go
- internal/params/tuple.go
- internal/params/tuple_test.go
Issue Number: #1061
- Support for the 'Tuple' type has been added to ydb.ParamsBuilder() for use in typed named expressions.
> Added `Tuple` support for `ydb.ParamsBuilder()`

- CHANGELOG.md
- internal/topic/retriable_error.go
- internal/topic/topicwriterinternal/writer_reconnector.go
Change default timeout for topic writer connection to a server.
> Default timeout for topic writer connection is infinite

- CHANGELOG.md
- options.go
for backward compatibility.
Issue Number: #1173 
-
-
-
> restored WithSessionPoolKeepAliveMinSize & WithSessionPoolKeepAliveTimeout

- internal/conn/conn.go
- internal/xcontext/cancels_quard.go
- internal/xcontext/cancels_quard_test.go
> added xcontext.CancelsGuard

- CHANGELOG.md
- internal/table/session.go
- internal/table/session_test.go
- table/options/options.go
- table/table.go
> * Supported `table.Session.RenameTables` method

- CHANGELOG.md
- credentials/credentials.go
- credentials/options.go
- examples/auth/README.md
- examples/auth/oauth2_token_exchange_credentials/README.md
- examples/auth/oauth2_token_exchange_credentials/main.go
- internal/credentials/oauth2.go
- internal/credentials/oauth2_test.go
- internal/credentials/source_info.go
- options.go
Implement OAuth 2.0 Token Exchange credentials provider in Go SDK
Issue Number: 3542
-
-
-
> Implement OAuth 2.0 Token Exchange credentials provider in Go SDK

- CHANGELOG.md
- log/context.go
- log/context_test.go
> Fixed data race using `log.WithNames`

- CHANGELOG.md
- internal/coordination/conversation/conversation.go
The current version may re-send original requests for already canceled conversations which may lead to inconsistency between the client and server state.
If a coordination service session re-attaches, idempotent conversations requests are being re-sent. However, if a conversation has been canceled, only its cancelation request must be re-send.
> fix: re-send cancel message on coordination session re-attach

- CHANGELOG.md
- internal/topic/topicwriterinternal/queue.go
- internal/topic/topicwriterinternal/writer_reconnector.go
- internal/topic/topicwriterinternal/writer_reconnector_test.go
- tests/integration/helpers_test.go
- tests/integration/topic_read_writer_test.go
- topic/topicwriter/topicwriter.go
Close writer right after call Close(...) and lost messages from a buffer
Flush messages before close
> Writer flush messages before close

- internal/xcontext/done.go
- internal/xcontext/done_test.go
- internal/xcontext/without_deadline.go
> added `xcontext.WithDone()` + replaced custom implementation `xcontext.ValueOnly()` to standard `context.WithoutCancel()`

- internal/cmd/gtrace/main.go
- internal/cmd/gtrace/writer.go
- internal/credentials/oauth2.go
- internal/credentials/static.go
- internal/decimal/decimal.go
- internal/value/nullable.go
- internal/value/value.go
- retry/sql.go
> Enable funlen linter (part 4)

- internal/credentials/static.go
- internal/grpcwrapper/rawtopic/rawtopicreader/rawtopicreader.go
- internal/pool/pool.go
- internal/scripting/client.go
- log/coordination.go
- log/driver.go
- log/query.go
- log/scripting.go
- log/sql.go
- log/table.go
- log/topic.go
> Enable funlen linter (part 5)

- CHANGELOG.md
- internal/dsn/dsn.go
- internal/dsn/dsn_test.go
Using empty database in ydb.Open with config.WithDatabase gives `configuration: empty database at github.com/ydb-platform/ydb-go-sdk/v3.(*Driver).connect(driver.go:389) at github.com/ydb-platform/ydb-go-sdk/v3.Open(driver.go:266)` error:
```go
ydbOpts := []ydb.Option{
ydb.WithDatabase("/local"),
}
_, err := ydb.Open(
ctx,
"grpc://localhost:2136",
ydbOpts...,
)
if err != nil {
panic(err.Error())
}
```
Like in older versions of SDK (3.65.3 for sure), the code above connects to /local database.
> Fixed empty database in DSN while using config.WithDatabase

- internal/query/config/config.go
- internal/query/session.go
- internal/query/transaction.go
> wrapped error BAD_SESSION in query session calls

- CHANGELOG.md
- internal/query/client.go
fixed nil pointer dereference when `resultToMaterializedResult` returned error
````
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xab2966]
```
returned error from `resultToMaterializedResult`
> Fix nil pointer dereference when closing result set.

- CHANGELOG.md
- internal/query/result_set.go
- tests/integration/query_multi_result_sets_test.go
```
query: non-retryable error occurred on attempt No.1 (idempotent=true): set 1: get next row: received part with result set index = 1, current result set index = 0: critical violation of the logic - wrong result set index at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*resultSet).nextRow(result_set.go:149)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.do.func1(client.go:126)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*poolStub).With.func2(client.go:83)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.Retry.func1(retry.go:264)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.opWithRecover(retry.go:411)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.RetryWithResult(retry.go:356)` at …
```
> Do not check ResultSetIndex when ResuilSet is nil.

- CHANGELOG.md
- credentials/options.go
- internal/credentials/oauth2.go
- internal/credentials/oauth2_test.go
OAuth 2.0 token exchange credentials provider fixes and improvements
* Don't take lock when performing http request
* Add retries
-
-
-
> [OAuth 2 token exchange] Don't take lock when performing http request. Add retries

- CHANGELOG.md
- metrics/table.go
Add metrics:
```
table.session.query.latency
table.session.query.errs
table.session.query.attempts
table.session.tx.latency
table.session.tx.errs
table.session.tx.attempts
```
Issue Number: 1318
Add metrics over table.Do and tabel.DoTx similar to query.Do and query.DoTx
> Metrics over table

- internal/empty/empty.go
> empty types are aliases now

- internal/xerrors/issues.go
Add Unwrap method for issues errors
We couldn't check issues inners errors. Add Unwrap method for issues errors
We could unwrap inner error for withIssuesError type. When i catch issues errors with DoTxWithResult call's, I want to sort errors by type so that they can be handled correctly. Add Unwrap method
> add: unwrap method for issues errors

- CHANGELOG.md
- examples/decimal/main.go
- table/types/cast_test.go
- table/types/value.go
Add new constructor for decimals from raw-string representation.
Issue Number: #1435 
- new types constructor added `DecimalValueFromString`
> feat: expose `DecimalValueFromString`

- CHANGELOG.md
- log/driver.go
```
2024-09-04 21:53:18.534 WARN 'ydb.driver.conn.stream.RecvMsg' => failed {"error":"EOF","latency":"1.173618216s","version":"3.77.0"}
```
this error is not logged
> Hide EOF error in recvMsg logs

- CHANGELOG.md
- internal/pool/defaults.go
- internal/pool/pool.go
- internal/pool/pool_test.go
- internal/pool/stats.go
- internal/pool/trace.go
- internal/query/client.go
- internal/table/client.go
- log/table.go
- metrics/table.go
- trace/query.go
- trace/query_gtrace.go
- trace/table.go
- trace/table_gtrace.go
> trace changes

- CHANGELOG.md
- internal/credentials/oauth2_test.go
- internal/pool/pool.go
- internal/table/retry_test.go
- retry/retry.go
> added lastErr from previous attemp in retry.RetryWithResult

- CHANGELOG.md
- balancers/balancers.go
- balancers/balancers_test.go
- balancers/config.go
- balancers/config_test.go
- internal/balancer/balancer.go
- internal/balancer/config/routerconfig.go
- internal/balancer/local_dc_test.go
> Added `balancers.PreferNearestDC[WithFallback]` balancers + Marked as deprecated `balancers.PreferLocalDC[WithFallback]` balancers

- query/example_test.go
- tests/integration/query_execute_test.go
> added test and example for explain query

- internal/query/client.go
- internal/query/options/retry.go
- tests/slo/internal/metrics/metrics.go
- tests/slo/internal/workers/read.go
- tests/slo/internal/workers/write.go
- tests/slo/native/query/main.go
> fixed log output for SLO

- CHANGELOG.md
- driver.go
```
2024-09-11T23:06:20.337+0300    WARN    middleware/errors.go:201        operation error {"app": "database", "request_id": "80c44aba-c7d5-4a67-89a6-55ca3c14100d", "method": "/Ydb.Operation.V1.OperationService/GetOperation", "operation_status": "TRANSPORT_ERROR", "issues": "", "grpc_status": "InvalidArgument", "error": "rpc error: code = InvalidArgument desc = Database not specified", "trace_id": "cb56e445d3a79eb3f233c8e006976537"}
```
User balancer connection with metadata
> Use balancer connection with metadata for operation service.

- CHANGELOG.md
- metrics/driver.go
metrics wer splitted to `ydb_go_sdk_ydb_driver_conn_request_methods` and `ydb_go_sdk_ydb_driver_conn_request_statuses`
-
-
-
> Split `ydb_go_sdk_ydb_driver_conn_requests` metrtcs

- CHANGELOG.md
- driver.go
> * Fixed connections pool leak on failed `ydb.Open` call

- CHANGELOG.md
- examples/topic/topicreader/topic_reader_transaction.go
- internal/topic/topicreaderinternal/batched_stream_reader_interface.go
- internal/topic/topicreaderinternal/batched_stream_reader_mock_test.go
- internal/topic/topicreaderinternal/reader.go
- internal/topic/topicreaderinternal/stream_reader_impl.go
- internal/topic/topicreaderinternal/stream_reconnector.go
- tests/integration/topic_transactions_test.go
- topic/topicreader/reader.go
> rename experimental method

- CHANGELOG.md
- internal/table/client.go
We skip rollback operation from ydb golang sdk because all DB server operation errors rollback from server. If we log error from underscore we could see new error as similar: `Transaction $transactionNumber not found`
Currently, we catch extra error for rollbacked transacrion
- skip rollback
> add: skip rollback

- CHANGELOG.md
- metrics/query.go
> Added `ydb_go_sdk_ydb_query_pool_size_limit` metrics

- CHANGELOG.md
- internal/query/client.go
- internal/query/client_test.go
- internal/query/config/config.go
- internal/query/config/options.go
- internal/query/session.go
- internal/topic/topicreaderinternal/transaction_mock_test.go
- internal/tx/id.go
- options.go
- query/example_test.go
- tests/integration/helpers_test.go
- tests/integration/query_tx_execute_test.go
> * Added `ydb.WithLazyTx()` option for create lazy transactions on `query.Session.Begin` call

- .github/workflows/tests.yml
- tests/integration/query_tx_execute_test.go
> fix tests + added integration tests for YDB 24.2

- CHANGELOG.md
- examples/topic/topicreader/topicreader_simple_iterators.go
- tests/integration/topic_helpers_test.go
- topic/topicsugar/cdc-reader.go
- topic/topicsugar/iterators.go
> some refactor of experimental topic helpers

- CHANGELOG.md
- internal/pool/errors.go
- internal/pool/pool.go
- internal/pool/pool_test.go
- internal/query/client.go
- internal/query/config/config.go
- internal/query/config/options.go
- internal/table/client.go
- internal/table/config/config.go
- options.go
> * Added `ydb.WithSessionPoolSessionUsageLimit()` option for limitation max count of session usage

- CHANGELOG.md
- driver.go
> * Fixed nil pointer dereference panic on failed `ydb.Open`

- CHANGELOG.md
- internal/topic/topicwriterinternal/writer_reconnector.go
- topic/topicwriter/topicwriter.go
> Returned `topicwriter.ErrQueueLimitExceed`, accidental removed at `v3.81.0`

- CHANGELOG.md
- internal/topic/topiclistenerinternal/stream_listener.go
- internal/topic/topiclistenerinternal/topic_listener_reconnector.go
> fix-listener-close

- CHANGELOG.md
- internal/meta/context.go
- internal/meta/headers.go
- meta/context.go
- tests/integration/connection_test.go
> * Added `meta.WithTraceParent` context modifier for explicit putting traceparent header into grpc calls

- CHANGELOG.md
- internal/table/session.go
- trace/table.go
- trace/table_gtrace.go
> * Added session info into `trace.TableSessionBulkUpsertStartInfo`

- tests/integration/query_regression_test.go
- tests/integration/table_regression_test.go
> canonization of current uuid behavior

- CHANGELOG.md
- internal/grpcwrapper/rawoptional/rawoptional.go
- internal/grpcwrapper/rawtopic/client.go
- internal/grpcwrapper/rawtopic/describe_consumer.go
- internal/topic/topicclientinternal/client.go
- tests/integration/topic_client_test.go
- topic/client.go
- topic/example_test.go
- topic/topicoptions/topicoptions_describe.go
- topic/topictypes/topictypes.go
- topic/topictypes/topictypes_test.go
It is impossible to get detailed topic consumer information. in YDB CLI, there is `topic consumer describe` method that allows user to get read/write lag timings, amount of read bytes per customer ets.
`Topic` client got `DescribeTopicConsumer` method that performs corresponding GRPC call to YDB and returns the data with minimal modification.
> add Topic.DescribeTopicConsumer

- internal/cmd/gtrace/writer.go
- trace/coordination_gtrace.go
- trace/discovery_gtrace.go
- trace/driver_gtrace.go
- trace/query_gtrace.go
- trace/ratelimiter_gtrace.go
- trace/retry_gtrace.go
- trace/scheme_gtrace.go
- trace/scripting_gtrace.go
- trace/sql_gtrace.go
- trace/table_gtrace.go
- trace/topic_gtrace.go
> trace.{}.Compose now can be called on nil

- .github/workflows/slo-report.yml
Add workflow for publishing slo test results
-
-
-
> ci: add workflow for publishing slo results 

- .github/workflows/tests.yml
> Do not run tests if label `no tests`

- CHANGELOG.md
- log/field.go
> returned field methods to public

- .github/workflows/slo.yml
- .gitignore
- tests/slo/database/sql/main.go
- tests/slo/gorm/main.go
- tests/slo/internal/metrics/metrics.go
- tests/slo/internal/metrics/span.go
- tests/slo/internal/workers/read.go
- tests/slo/internal/workers/workers.go
- tests/slo/internal/workers/write.go
- tests/slo/native/query/main.go
- tests/slo/native/table/main.go
- tests/slo/xorm/main.go
This update introduces a new GitHub Action designed to streamline Service Level Objective (SLO) testing across our range of SDKs. This integration aims to enhance our development and testing workflows by providing automated, consistent SLO testing capabilities directly within the CI/CD pipeline.
- ### New GitHub Action: 
- Welcome: https://github.com/ydb-platform/ydb-slo-action 
- Implemented a GitHub Action specifically for conducting SLO tests.
- Automates the testing process, enhancing reliability and efficiency.
- ### Improvements Over Previous System:
- The new action now supports execution in forked repositories, unlike the previous setup that relied on external closed infrastructure and couldn't handle report submissions from forks.
- Operates entirely on GitHub Actions …
> Add New GitHub Action for SLO Tests Integration with SDK

- .github/workflows/slo.yml
- tests/slo/internal/metrics/metrics.go
> Run SLO Tests on push master

- CHANGELOG.md
- balancer.go
- driver.go
- internal/balancer/balancer.go
- options.go
>     Added balancer with metadata customization

- CHANGELOG.md
- context.go
- internal/conn/middleware.go
- internal/operation/context.go
- internal/pool/pool.go
- internal/pool/pool_test.go
- internal/query/client.go
- internal/query/client_test.go
- internal/table/client.go
- internal/table/retry_test.go
Server has ability to return node id during table describe
https://github.com/ydb-platform/ydb/pull/10935
It allows to reduce number of network transfers.
This is initial implementation of client support for this feature.
> Allow to set preferred node id to execute query

- internal/stack/function_id.go
- internal/stack/function_id_test.go
- internal/stack/record.go
- internal/stack/record_test.go
- retry/retry.go
- spans/discovery.go
- spans/driver.go
- spans/query.go
- spans/retry.go
- spans/scheme.go
- spans/scripting.go
- spans/sql.go
- spans/table.go
- trace/call.go
> rename call.FunctionID() to call.String()

- CHANGELOG.md
- internal/query/execute_query.go
- internal/query/options/execute.go
- internal/query/result.go
- internal/query/result_set.go
- internal/query/result_test.go
- query/execute_options.go
- tests/integration/query_execute_test.go
- tests/integration/query_regression_test.go
> Fixed error with incompleted data returen from transaction.ReadQueryResult method

- CHANGELOG.md
- internal/pool/pool.go
Because of goroutine used context, which was closed in defer, item.Close wasn't closing session in table client, but delete it from pool. It causes session leak. This pr fixed this.
> Fix pool item close

- CHANGELOG.md
- internal/pool/pool.go
All YDB errors are retryable now with no exceptions. This causes hanging of `driver.Table().Do()` calls in case if invalid credentials were provided.
Issue Number: #1550.
Errors with code `UNAUTHORIZED` are returned immediately to the caller.
Fixes #1550 and YQ-3843.
> Avoid retrying requests finished with 'UNAUTHORIZED' errors

- examples/go.mod
- examples/go.sum
- go.mod
- go.sum
- scheme/scheme.go
- tests/slo/go.mod
- tests/slo/go.sum
> Add patitioning info to describe table

- CHANGELOG.md
- internal/table/session.go
So we know real status when delete fails
Right now, when ydb.table.session.delete fails, session status is always "closed", because it sets right before logging, so we do not know if we are closing a session twice, or there is some kind of different error.
Status is changed to closed only after logging it.
> update session status only after logging it

- CHANGELOG.md
- internal/pool/pool.go
Fixed context which is used for closing session with timeout
pool spawns new goroutine for closing session, but for creating context with timeout it uses original, user context, which may be closed
it uses context whithout cancel, and should works propely
-
-
-
> fix context which is used for closing session

- CHANGELOG.md
- internal/query/execute_query.go
- internal/query/result.go
> * Fixed goroutine leak on failed execute call in query client

- CHANGELOG.md
- internal/xsql/legacy/tx.go
- internal/xsql/tx.go
SDK panics when it tries to log a span on non-existing xsql.tx. Backtraces are like this:
```
goroutine 171969 [running]:
runtime/debug.Stack()
GOROOT/src/runtime/debug/stack.go:26 +0x5e
nebius.ai/nebo/msp/internal/grpc.NewServer.recoveryLogger.func4({0x4685130, 0xc0041e74d0}, {0x36275e0, 0x74ed7f0})
msp/internal/grpc/server.go:51 +0x14e
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0x4685130?, 0xc0041e74d0?}, {0x36275e0?, 0x74ed7f0?}, 0xc003c51810?)
external/gazelle~~go_deps~com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:61 +0x30
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1()
external/gazelle~~go_deps~com_github_grpc_ecosystem_go_grpc_middleware/recovery/ …
```
> fix panic in span reporting

- CHANGELOG.md
- internal/query/client.go
- internal/query/client_test.go
- internal/query/session.go
- internal/query/transaction.go
- internal/version/version.go
- tests/integration/query_regression_test.go
> 1607 bad session on error

- CHANGELOG.md
- internal/xslices/keys.go
- internal/xslices/keys_test.go
- internal/xsql/conn.go
- internal/xsql/connector.go
- internal/xsql/options.go
- metrics/sql.go
- metrics/traces.go
- tests/integration/database_sql_metrics_test.go
- tests/integration/database_sql_regression_test.go
- tests/integration/table_truncated_err_test.go
- trace/sql.go
- trace/sql_gtrace.go
Counter `ydb_go_sdk_ydb_database_sql_conns` goes in negative values when `database/sql` driver is used. The reason is [after this commit](https://github.com/ydb-platform/ydb-go-sdk/commit/fd4142df6e70e949cc2b141bdc358d27473f69f9#diff-bc3f866611d992e908970b6cc021a96cb80ac60cbe0afd9372284c9713add5c3R51), `OnConnBeginTx` is called on begin, `OnConnClose` called on close, gauge is only decremented, and `database/sql` driver in sdk does not have its own `OnConnBeginTx` implementation, so it does nothing
Restores the behaviour before the mentioned commit
> fix broken metric `ydb_go_sdk_ydb_database_sql_conns`

- retry/sql.go
- retry/sql_test.go
> processing of panics in retriers

- internal/balancer/balancer.go
> dedicaded close message for internal balancer closed

- CHANGELOG.md
- driver.go
- internal/repeater/repeater.go
- internal/xsql/connector.go
- internal/xsql/options.go
- options.go
- sql.go
- tests/integration/basic_example_database_sql_bindings_test.go
- tests/integration/basic_example_database_sql_test.go
- tests/integration/helpers_test.go
> * Fixed goroutine leak on closing `database/sql` driver

- CHANGELOG.md
- internal/value/any.go
- internal/value/any_test.go
> * Returned legacy behaviour for interpret as `time.Time` YDB types `Date`, `Datetime` and `Timestamp`

- CHANGELOG.md
- go.mod
- internal/grpcwrapper/rawoptional/rawoptional.go
- internal/grpcwrapper/rawtopic/describe_consumer.go
- tests/integration/topic_client_test.go
- topic/topictypes/topictypes_test.go
Fixes describe consumer operation, so that it would parse partition consumer stats
Describe consumer operation doesn't process PartitionConsumerStats
Describe consumer operation does process PartitionConsumerStats
> Fix describe consumer not parsing partition consumer stats

- internal/xtest/leak.go
- internal/xtest/leak_test.go
> Small changes in detector goroutines leak

- CHANGELOG.md
- dsn.go
- dsn_test.go
- internal/bind/auto_declare.go
- internal/bind/bind.go
- internal/bind/noop.go
- internal/bind/numeric_args.go
- internal/bind/numeric_args_test.go
- internal/bind/params.go
- internal/bind/params_test.go
- internal/bind/positional_args.go
- internal/bind/positional_args_test.go
- internal/bind/sql_lexer.go
- internal/bind/table_path_prefix.go
- internal/bind/wide_time_types.go
- internal/bind/wide_time_types_test.go
- internal/bind/wide_types.go
- internal/bind/wide_types_test.go
- internal/params/builder.go
- internal/params/parameters.go
- internal/value/value.go
- query_bind_test.go
- sql.go
> * Added binding `ydb.WithWideTimeTypes()` which interprets `time.Time` and `time.Duration` as `Timestamp64` and `Interval64` YDB types

- CHANGELOG.md
- metrics/query.go
Fixed bug with session query latency metric collector
-
-
-
> Fixed bug with session query latency metric collector

- CHANGELOG.md
- internal/grpcwrapper/rawtopic/describe_topic.go
- tests/integration/topic_client_test.go
- topic/topicoptions/topicoptions_describe.go
- topic/topictypes/topictypes.go
- topic/topictypes/topictypes_test.go
Added an option do describe topic partition stats
no possibility to get partition stats for topic
Added `topicoptions.IncludePartitionStats()` for `Topic().Describe()` that gets and parses topic partition stats
> describe topic partition stats

- CHANGELOG.md
- internal/bind/bind.go
- internal/bind/params.go
- tests/integration/database_sql_json_test.go
> * Supported `json.Marshaller` query parameter in `database/sql` driver

- tests/integration/topic_read_writer_test.go
Temporary skip test for nightly YDB as workaround of: https://github.com/ydb-platform/ydb/issues/19449
> skip test for nigtly version for bug workaround

- CHANGELOG.md
- internal/value/cast_test.go
- internal/value/value.go
**-**
query.Row.ScanStruct supports json.Marshaller, but it does not work in the reverse direction (when receiving data from the database), for this purpose I add json.Unmarshaler for convenient work with QueryClient.
**-**
> added json unmarshaler for castTo

- CHANGELOG.md
- internal/value/value.go
- internal/value/value_test.go
Fixed incorrect string conversion of `Uint64Value` values greater than `int64` max value
Issue Number: #1842
When cast Uint64Value with val 9223372036854775808 to string, the string value is 9223372036854775808
> Fixed incorrect string conversion of `Uint64Value` values greater than `int64` max value

- CHANGELOG.md
- retry/sql.go
- retry/sql_test.go
Fix bug when DoTxWithResult sometimes returns ErrTxDone on context cancellation
When context was cancelled before Commit() call in DoTxWithResult, goroutine in database/sql: sql.go:2221 rollbacks the transaction. When SDK code calls Commit after that, it sees that tx was already rollbacked and throws ErrTxDone instead of context error, DoTxWithResult throws this error up. 
DoTxWithResults catches ErrTxDone and if context contains error, it throws up context error instead. This behaviour looks correct, because tx created just in this method and couldn't be commited or rolled back in any other way.
> Catch ErrTxDone in DoTxWithResult

- CHANGELOG.md
- internal/topic/topicreaderinternal/stream_reader_impl.go
Errors in the UpdateOffsetsInTransaction method are not tracked.
> Fix error logging for UpdateOffsetsInTransaction

- CHANGELOG.md
- internal/conn/pool.go
- internal/endpoint/endpoint.go
If YDB server uses public IP addresses in ListEndpoints response, old IPs are not removed from connection pool (due to `endpoint.Key()` using `e.address` instead of resolved address). And, after a rolling restart of YDB dynnodes, if all of them get new IPs, database becomes unavailable.
- `conns/pool.Get()` now stores endpoints based on resolved IP, not on address, if that is possible
> use resolved address instead of address in conn/pool

- CHANGELOG.md
- internal/query/scanner/struct_test.go
- internal/value/value.go
- tests/integration/query_execute_test.go
Issue Number: 1785
-
-
-
fix scan a YDB column of type Decimal(22,9) into a struct field of type types.Decimal using ScanStruct. example in query_execute_test.go (TestIssue1785FillDecimalFields)
> fix fill decimal
