errors.go
=> add StatusAlreadyExists error

internal/scheme/scheme.go
=> add scheme helpers

errors.go
=> status already exists

errors.go
=> status scheme2

errors.go
=> iterate by issues

internal/table/scanner/result.go, internal/table/scanner/result_test.go, table/resultset/result.go
=> publish result set

config/config.go, connect_params.go, connection.go, internal/dial/dialer.go, internal/dial/discovery.go, internal/driver/cluster/balancer/conn/conn.go, internal/driver/cluster/balancer/conn/runtime/runtime.go, internal/driver/cluster/balancer/rr_test.go, internal/driver/cluster/balancer_test.go, internal/driver/cluster/cluster.go, options.go, trace/driver.go, trace/driver_gtrace.go
=> traces fixes + fix stream done

CHANGELOG.md, internal/discovery/discovery.go, internal/driver/cluster/balancer/conn/endpoint/endpoint.go, internal/driver/cluster/cluster.go, internal/driver/cluster/cluster_test.go, internal/meta/version.go
=> fix endpoints compare func

README.md
Fixed some bugs in usage example.
=> Update usage example in README.md

CHANGELOG.md, go.mod, internal/meta/version.go, table/options/options.go, trace/details.go
Added `table.option.WithPartitioningSettings`
Issue Number: #37 
-
-
-
=> Partition settings and `trace.DriverConnEvents` constant

CHANGELOG.md, internal/meta/version.go, internal/table/session.go, log/table.go, trace/table.go, trace/table_gtrace.go
=> Fixed logic bug in `trace.Table.ExecuteDataQuery{Start,Done}Info`

CHANGELOG.md, internal/errors/operation.go, internal/meta/version.go, retry/retry_test.go
=> Fixed retry reaction on operation error NotFound (non-retryable now)

CHANGELOG.md, errors.go, internal/errors/operation.go, internal/errors/transport.go, internal/meta/version.go
=> Simplify Is{Transport,Operation}Error, add IsYdbError + merge v2 changes

.github/workflows/gosec.yml, config/config.go, internal/driver/cluster/balancer/balancer.go, internal/driver/cluster/balancer/rr.go, internal/rand/rand.go, options.go, retry/retry.go, sugar/sugar.go, testutil/session.go
=> add gosec action + fix gosec issues

.github/workflows/tests.yml, test/ratelimiter_test.go, test/table_test.go
=> iverted build tag fast

CHANGELOG.md, config/config.go, internal/meta/version.go, internal/table/scanner/result.go, internal/table/session.go, options.go, sugar/sugar.go
* Added system certificates for `darwin` system
* Fixed `table.StreamResult` finishing
* Fixes `sugar.MakePath()`
* Added helper `ydb.MergeOptions()` for merge several `ydb.Option` to single `ydb.Option`
-
-
-
=> draft v3.5.1

CHANGELOG.md, internal/logger/log.go, internal/meta/version.go, internal/table/client_test.go, internal/table/session.go, log/driver.go, log/log.go, log/table.go, options.go
=> changed logger API + add public type LoggerOption

CHANGELOG.md, internal/meta/version.go, internal/table/scanner/result.go, internal/table/session.go
=> Added auto-close stream result on end of stream

CHANGELOG.md, config/balancer/balancer.go, internal/discovery/discovery.go, internal/endpoint/endpoint.go, test/table_test.go
=> Added new `PreferLocations[WithFallback][RegEx]` balancers

CHANGELOG.md, trace/details.go, trace/details_test.go
=> trace.Details.String() and trace.DetailsFromString()

config/config.go, internal/cluster/cluster_test.go, internal/decimal/decimal.go, internal/scripting/scripting.go, internal/table/client_test.go, internal/table/scanner/scanner.go, internal/table/scanner/scanner_test.go, internal/table/session_test.go, internal/value/type.go, internal/value/value.go, log/driver.go, log/table.go, retry/retry_test.go, test/table_test.go
=> Fix internal log messages isolation

CHANGELOG.md, internal/meta/version.go, sugar/sugar.go
* Retry remove directory in sugar.RemoveRecursive for retriable error
=> remove-overload

CHANGELOG.md, internal/meta/version.go, internal/table/retry_test.go, internal/table/scanner/perfomance_test.go, internal/table/scanner/result_test.go, internal/table/scanner/scan_raw.go, internal/table/scanner/scanner.go, internal/table/scanner/scanner_data_test.go, internal/table/scanner/scanner_test.go, table/result/result.go, test/table_test.go
=> table.Result.ScanNamed()

internal/cluster/cluster_test.go, internal/table/retry_test.go, test/ratelimiter_test.go, test/scripting_test.go, test/table_test.go, trace/details_test.go
=> fix sub-test names

CHANGELOG.md, internal/table/retry.go, internal/table/scanner/scanner.go, internal/table/scanner/scanner_data_test.go, internal/table/scanner/scanner_test.go, table/result/indexed/indexed.go, table/result/result.go
=> refactoring of package indexed

.github/workflows/tests.yml, CHANGELOG.md, internal/table/client.go, internal/table/retry.go, internal/table/retry_test.go, internal/table/trailer.go, test/ratelimiter_test.go, test/table_test.go
=> session close hint process

internal/table/session.go, internal/table/trailer.go, table/client.go, test/table_test.go
=> rename trailer.Check to trailer.processHints

internal/table/data_query.go, internal/table/keep_in_cache.go, internal/table/keep_in_cache_test.go, internal/table/session.go, internal/table/session_test.go, internal/table/statement.go, internal/table/transaction.go, internal/table/transaction_test.go
=> split session.go to {transaction,data_query,statement,keep_in_cache}.go

CHANGELOG.md, config/config.go, internal/meta/version.go, options.go, test/scripting_test.go
=> add WithMinTLSVersion

CHANGELOG.md, config/config.go, internal/meta/version.go
=> v3.9.2: single conn balancer

CHANGELOG.md, internal/logger/log.go, internal/meta/version.go
=> v3.9.3: fix busy loop in internal logger with external log.Logger implementation

CHANGELOG.md, connection.go, internal/meta/meta.go, internal/meta/version.go, internal/proxy/coordiantion.go, internal/proxy/discovery.go, internal/proxy/ratelimiter.go, internal/proxy/scheme.go, internal/proxy/scripting.go, internal/proxy/table.go, meta.go, proxy.go
=> v3.11.0: WithCustomOptions()

CHANGELOG.md, connection.go, internal/ratelimiter/ratelimiter.go, options.go, ratelimiter/config/config.go
=> WithRatelimiterOptions() + redefine operation.Params.Timeout and operation.Params.CancelAfter in ratelimiter client

CHANGELOG.md, custom_options.go
=> WithCustomCredentials

CHANGELOG.md, config/config.go, internal/resolver/resolver.go, log/driver.go, test/table_test.go, trace/details.go, trace/details_test.go, trace/driver.go, trace/driver_gtrace.go
=> add resolver trace callback + trace.MatchDetails(pattern)

internal/cluster/cluster.go, internal/conn/conn.go
=> mini-fix in cluster.Get

errors.go, internal/ratelimiter/errors/errors.go, internal/ratelimiter/ratelimiter.go, ratelimiter/errors.go
=> get AcquireError to public

CHANGELOG.md, internal/cluster/cluster.go, internal/conn/pool.go, internal/discovery/discovery.go, internal/meta/version.go, test/table_test.go
=> lock cluster for update endpoints

CHANGELOG.md, connection.go, proxy.go
=> revert grpc.ClientConnInterface API to ydb.Connection

CHANGELOG.md, internal/meta/version.go, proxy.go
=> replace meta in proxyConnection.Invoke and proxyConnection.NewStream

CHANGELOG.md, internal/meta/meta.go, internal/meta/version.go, log/driver.go, log/secret.go, trace/driver.go, trace/driver_gtrace.go
=> v3.11.6: token representation + `log.Secret` helper for mask token

CHANGELOG.md, errors.go, internal/errors/operation.go, internal/meta/version.go
=> removed internal alias-type errors.IssuesIterator

.github/workflows/tests.yml, CHANGELOG.md, connection.go, internal/balancer/stub/stub.go, internal/balancer/test/balancer_test.go, internal/cluster/cluster.go, internal/conn/conn.go, internal/conn/context.go, internal/conn/grpc_client_stream.go, internal/conn/pool.go, internal/errors/grpc.go, internal/errors/operation.go, internal/errors/transport.go, log/driver.go, test/connection_test.go, trace/driver.go, trace/driver_gtrace.go
=> no wrapping non-success operation results for use Connection as grpc.ClientConnInterface

CHANGELOG.md, internal/balancer/rr/rr.go, internal/meta/version.go, internal/rand/rand.go, internal/repeater/test/repeat_test.go, internal/table/client_test.go, internal/table/retry_test.go, internal/table/scanner/scanner_test.go, retry/retry.go, retry/retry_test.go, testutil/session.go
=> v3.11.11: Reverted usage of `math/rand` (instead `crypto/rand`)

CHANGELOG.md, balancers/balancer.go, internal/meta/version.go
=> balancers.Prefer + balancers.PreferWithFallback

CHANGELOG.md, balancers/config.go, balancers/config_test.go, internal/meta/version.go
=> v3.14.0: balancers.FromConfig

CHANGELOG.md, balancers/config.go, balancers/config_test.go, internal/balancer/balancer.go, internal/balancer/multi/multi.go, internal/balancer/stub/stub.go, internal/meta/version.go, with.go
=> v3.14.1: balancers.CreateFromConfig + balancer.Balancer.Create

CHANGELOG.md, internal/cluster/cluster.go, internal/meta/version.go
=> v3.14.3: Fixed bug with update balancer element with nil handle

CHANGELOG.md, internal/conn/conn.go, internal/conn/grpc_client_stream.go, internal/endpoint/endpoint.go, internal/errors/transport.go
=> v3.14.5: transport error details and address

CHANGELOG.md, internal/balancer/multi/multi.go, internal/cluster/cluster.go, internal/conn/conn.go, internal/conn/pool.go, internal/discovery/discovery.go, internal/errors/transport.go, internal/ratelimiter/ratelimiter.go
=> v3.14.5: minifixes from https://github.com/ydb-platform/ydb-go-sdk/pull/160

.github/workflows/tests.yml, CHANGELOG.md, internal/conn/config.go, internal/conn/conn.go, internal/conn/grpc_client_stream.go, internal/conn/pool.go, internal/db/database.go, log/driver.go, test/connection_test.go, test/discovery_test.go, trace/driver.go, trace/driver_gtrace.go
=> v3.14.5: stream usages

CHANGELOG.md, errors.go, internal/conn/conn.go, internal/db/database.go, internal/errors/errors.go, internal/errors/grpc.go, internal/errors/grpc_test.go, internal/errors/issues.go, internal/errors/operation.go, internal/errors/operation_test.go, internal/errors/stacktrace.go, internal/errors/stacktrace_test.go, internal/errors/transport.go, internal/errors/ydb.go, internal/errors/ydb_test.go, internal/table/client.go, internal/table/client_test.go, internal/table/retry.go, retry/retry.go, retry/retry_test.go, sugar/sugar.go, table/options.go, test/discovery_test.go, test/table_test.go
=> revert meta apply in internal/db/database.{Invoke,NewStream}

.github/workflows/publish.yml, CHANGELOG.md, internal/meta/meta.go, internal/meta/test/meta_test.go, internal/meta/version.go, log/driver.go, table/types/value.go, table/types/value_test.go, version.go
=> add Nullable*Value helpers and Nullable() entrypoint for all values

CHANGELOG.md, internal/logger/level/level.go, internal/table/client.go, internal/table/retry.go, log/retry.go, log/table.go, retry/retry.go, test/table_test.go
* Removed all conditions for trace retry errors
* Fixed background color of warn messages
* Added to log messages additional information about error, such as retryable (or not), delete session (or not), etc.
-
-
-
=> print retry causes

.github/workflows/publish.yml, CHANGELOG.md, config/config.go, internal/conn/config.go, internal/conn/conn.go, internal/net/conn.go, internal/resolver/resolver.go, test/table_test.go
=> Dont use dns resolver

CHANGELOG.md, connection.go, discovery/config/config.go, internal/discovery/discovery.go
=> bugfix with credentials on discovery

CHANGELOG.md, internal/db/database.go, internal/meta/meta.go, table/types/value.go, table/types/value_test.go
* Refactored package `meta`
* Removed explicit call meta in `db.New()`
-
-
-
=> * Fixed bug in `types.Nullable()`

CHANGELOG.md, internal/cluster/cluster.go
=> Replaced panic on cluster close to error issues

CHANGELOG.md, internal/cluster/cluster.go
=> banned -> online on cluster.Update

CHANGELOG.md, with.go
=> Removed unnecessary options append in ydb.With

CHANGELOG.md, config/config.go, connection.go, internal/conn/pool.go, internal/db/database.go, test/discovery_test.go, with.go
=> Remove opts append + SharedPool

CHANGELOG.md, config/config.go, internal/conn/conn.go, internal/conn/grpc_client_stream.go, internal/conn/pool.go, internal/db/database.go, internal/errors/issues.go, internal/errors/operation.go, internal/errors/transport.go, internal/errors/transport_test.go, retry/retry_test.go
=> MapGRPCError -> FromGRPCError + pessimization node conditions

.github/workflows/publish.yml, CHANGELOG.md
=> Added full changelog link to github release description

.github/workflows/tests.yml, CHANGELOG.md
=> add go 1.18 to tests

CHANGELOG.md, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cmd/gtrace/main.go, internal/conn/conn.go
=> * Added address to error description which thrown from `conn.take()`

CHANGELOG.md, NEXT_MAJOR_RELEASE.md, internal/meta/meta.go, internal/meta/version.go, internal/xerrors/ydb.go, log/coordination.go, log/discovery.go, log/driver.go, log/ratelimiter.go, log/retry.go, log/scheme.go, log/scripting.go, log/table.go, version.go
=> Add version to all warn and error calls

CREDENTIALS.md, DEBUG.md, ENVIRON.md, NEXT_MAJOR_RELEASE.md, README.md, example_table_test.go, ydb.go
=> Refactored README.md and godoc documentation

CHANGELOG.md, dsn/dsn.go, dsn/parser.go, options.go
=> add package dsn

.github/workflows/breaking.yml, CHANGELOG.md, config/config.go
=> * Used anonymous credentials by default

CHANGELOG.md, internal/balancer/rr/rr.go, internal/balancer/test/balancer_test.go, internal/xrand/xrand.go
Many code for accounting load factor, but load factor never send by server.
Same behaviour, but without accounting load factor - code much simpler.
=> Remove accounting loadfactor from balancer

.github/workflows/gtrace.yml, .github/workflows/lint.yml, .github/workflows/tests.yml
Double run tests for pr: on push to tmp branch + on pull request, run tests for tags
Run tests, linter, etc for pr only. It prevent double run tests (for pr and for branch push).
=> remove unneeded actions runs

internal/conn/conn.go
=> comment about ///

README.md
Refactoring readme md by markdown styles
=> fix: markdown file style

CHANGELOG.md, connection.go, internal/conn/conn.go, internal/dsn/dsn_test.go, options.go, sugar/dsn.go, sugar/dsn_test.go, test/connection_test.go, testutil/assert.go
Reimplement sugar.DSN with net/url
Accidentally trim trailing spaces in CHANGELOG.md
-
-
-
=> Reimplement sugar.DSN with net/url

CHANGELOG.md, internal/table/scanner/scanner.go, internal/table/scanner/scanner_test.go, table/result/indexed/indexed.go, table/result/result.go
=> Json unmarshaler

CHANGELOG.md, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/repeater/repeater.go, internal/router/router.go, internal/timeutil/time.go, log/driver.go, trace/driver.go, trace/driver_gtrace.go
=> fix race on cluster close

CHANGELOG.md, connection.go, connection_e2e_test.go
=> * Removed from `ydb.Connection` embedding of `grpc.ClientConnInterface`

CHANGELOG.md, internal/table/keep_in_cache_test.go, internal/table/session.go, table/options/options.go, table/table.go, table/table_e2e_test.go
* Marked as deprecated `session.Prepare` callback
* Marked as deprecated `options.WithQueryCachePolicyKeepInCache` and `options.WithQueryCachePolicy` options
* Added `options.WithKeepInCache` option
* Enabled by default keep-in-cache policy for data queries
-
-
-
=> Enabled by default keep-in-cache

CHANGELOG.md, connection.go, connection_e2e_test.go
=> ydb.GRPCConn(ydb.Connection)

CHANGELOG.md, connection.go, discovery/discovery_e2e_test.go, internal/backoff/backoff_test.go, internal/conn/conn.go, internal/repeater/repeater.go, internal/repeater/repeater_test.go, internal/router/router.go, internal/table/session.go, retry/retry_test.go
=> * Implemented log backoff for force repeater wakeup's + meybe fix of race on read trailing metadata

internal/timeutil/time.go
=> revert time.Duration <-> int64 convertation

CHANGELOG.md, LICENSE, NOTICE, README.md
=> Change primary license to Apache-2.0

.golangci.yml
remove deprecated linter maligned
=> remove deprecated linter

CHANGELOG.md, scheme/scheme.go
=> Refactored of making permissions from scheme entry

CHANGELOG.md, table/table.go
* Added comments for `table/session.Execute` method
-
-
-
=> * Removed `Deprecated` mark from `table/session.Prepare` method

CHANGELOG.md, go.mod, go.sum
=> * Update indirect dependency to `gopkg.in/yaml.v3`

CHANGELOG.md, internal/table/keep_in_cache_test.go, internal/table/session.go, table/table.go
=> * Disabled the `KeepInCache` policy for queries without params

CHANGELOG.md, go.mod, go.sum
=> * Updated the genproto dependency

table/table_regress_test.go
Check about duration go time convert to server type interval as microseconds
Add test about after convert duration to server type datetime arithmetics work wight with the converted value.
=> check interval type with datetime arithmetic

CHANGELOG.md, internal/table/scanner/result.go, internal/table/scanner/stats.go, table/options/options.go, table/result/result.go, table/stats/stats.go, table/table_e2e_test.go
* Added to query stats plan and AST
-
-
-
=> * Added `options.WithExecuteScanQueryStats` option

.github/workflows/tests.yml, CHANGELOG.md, internal/dsn/dsn.go, internal/dsn/dsn_test.go
=> * Supported parsing of database name from connection string URI path

CHANGELOG.md, sugar/params.go, sugar/params_test.go, table/table.go
=> add sugar.GenerateDeclareSection(params)

CHANGELOG.md, config/config.go, internal/conn/conn.go, internal/conn/grpc_client_stream.go, internal/conn/pool.go, internal/retry/mode.go, internal/xerrors/retryable.go, internal/xerrors/transport.go, retry/retry_test.go
=> Retry dialing errors

README.md
=> Added installation info to README

CHANGELOG.md, balancers/balancers.go, balancers/balancers_test.go, config/config.go, internal/balancer/balancer.go, internal/balancer/local_dc.go, internal/discovery/discovery.go, internal/meta/context.go, internal/meta/meta.go, internal/meta/test/meta_test.go, internal/table/client.go, sugar/path.go, table/table_e2e_test.go
=> * Added session balancer hint to client capabilities in metadata headers

CHANGELOG.md, internal/mock/conn.go, internal/value/type.go, table/types/types.go, table/types/types_test.go
=> fixed types.WriteTypeStringTo + added TestWriteTypeStringTo test

.github/workflows/check-codegen.yml, .github/workflows/gtrace.yml, CHANGELOG.md, internal/table/session.go, internal/table/statement.go, trace/table_gtrace.go
regenerate and check equals for generate gtrace only
run go generate and check equals for all ydb-go-sdk folder
=> fix check codegen code

CHANGELOG.md, internal/meta/meta.go, internal/meta/test/meta_test.go
=> Supported many user-agent records

CHANGELOG.md, internal/table/client.go, internal/table/client_test.go, internal/table/retry_test.go, internal/table/session.go, table/table.go
=> Refactoring of `db.Table().CreateSession()`

.github/workflows/breaking.yml, .github/workflows/check-codegen.yml, .github/workflows/lint.yml, .github/workflows/tests.yml
Check test, builds for go 1.14-1.18
Check test, builds for go 1.14,1.18,1.19
=> add check go 1.19 in ci

trace/details.go, trace/topic.go
Fix inconsistent topic events name
=> fix topic events mask name

internal/balancer/balancer.go, internal/balancer/connections_state.go, internal/conn/conn.go, internal/conn/pool.go, table/table_e2e_test.go
=> refactored locks of conn pool and conn for fix TestTable

CHANGELOG.md, internal/background/worker.go, internal/table/client.go, internal/table/client_test.go, internal/table/retry.go, internal/table/retry_test.go, internal/table/scanner/result.go, internal/table/session.go, internal/xtest/manytimes.go, log/table.go, table/options/models.go, table/table.go, table/table_e2e_test.go, testutil/driver.go, trace/table.go, trace/table_gtrace.go
=> refactored session lifecycle in pool

.github/workflows/tests.yml, CHANGELOG.md, internal/xsql/bad_conn.go, internal/xsql/bad_conn_go1.18.go, internal/xsql/conn.go, internal/xsql/connector.go, internal/xsql/context.go, internal/xsql/errors.go, internal/xsql/isolation.go, internal/xsql/mode.go, internal/xsql/rows.go, internal/xsql/stmt.go, internal/xsql/tx.go, internal/xsql/xsql.go, sql.go, sql_e2e_test.go, table/result/result.go, table/table_e2e_test.go
=> Implemented `database/sql` driver over `ydb-go-sdk`

CHANGELOG.md, README.md, connection.go, connection_test.go, example_test.go, options.go, sql.go, sugar/dsn.go, sugar/dsn_test.go, topic/example_test.go
=> fix connection strings

internal/xsql/conn.go, internal/xsql/tx.go, sql_e2e_test.go
=> fix call tx

internal/xsql/conn.go, retry/sql.go, retry/sql_test.go, sql_e2e_test.go
=> added test for Operation error ABORTED (Transaction locks invalidated)

internal/xsql/badconn/badconn_go1.18.go
=> removed method badconn.badConnError.Unwrap

internal/table/scanner/result.go
=> early exit from NextResultSetErr

.gitignore, CHANGELOG.md, internal/grpcwrapper/rawtopic/describe_topic.go, topic/client_e2e_test.go, topic/example_test.go, topic/reader_e2e_test.go, topic/topictypes/topictypes.go
=> [topic] fix missprint for topictypes

CHANGELOG.md, internal/table/client.go, internal/table/client_test.go, internal/table/config/config.go, internal/table/errors.go, internal/table/retry.go, internal/table/session.go, internal/xerrors/issues.go, log/options.go, log/table.go, options.go, table/options/models.go, table/table_e2e_test.go, table/table_regress_test.go, testutil/timeutil/timetest/timetest.go, testutil/timeutil/timeutil.go, trace/table.go, trace/table_gtrace.go
=> refactoring of closing sessions in pool

CHANGELOG.md, internal/xsql/badconn/badconn_go1.18.go, retry/errors_go1.18.go
=> * Refactored the xsql.badconn.Error

topic/topictypes/topictypes.go
=> remove unused method in internal topic api

CHANGELOG.md, log/loglevel.go, log/topic.go
Add logging for topic api reader for internal logger
=> add topic logging

internal/xtest/grpclogger.go
=> Grpc logger

CHANGELOG.md, internal/retry/check.go, internal/xtest/grpclogger.go, retry/errors_data_test.go
=> revert context errors as required delete session

internal/xsql/badconn/badconn_go1.18.go, internal/xsql/conn.go, sql_e2e_test.go
=> refactoring of xsql.conn.checkClosed + add TestRegressionCloud109307

CHANGELOG.md, config/config.go, connection.go, internal/topic/topicclientinternal/client.go, internal/topic/topicreaderinternal/reader.go
Send update token message with empty token
Send update token message with token from ydb.Connection
=> fixed update token for topic reader

CHANGELOG.md, internal/topic/topicwriterinternal/writer_reconnector.go, log/topic.go, trace/details.go, trace/topic.go, trace/topic_gtrace.go
=> added internal topic writer logging

.github/workflows/lint.yml
run linter for every go version
run linter once
=> remove linter for versions matrix

internal/topic/topicreaderinternal/stream_reader_impl.go, topic/topic_read_writer_e2e_test.go
Skip topic writer tests with ydb docker image
run topic writer tests with ydb docker image
=> enable topic writer integration tests in public ci

internal/topic/topicclientinternal/client.go, internal/topic/topicreaderinternal/partition_session.go, internal/topic/topicreaderinternal/reader.go, internal/topic/topicwriterinternal/writer_options.go, internal/xtest/logs.go, topic/cdc_reader_e2e_test.go, topic/client_e2e_test.go, topic/topic_read_writer_e2e_test.go
=> fixed topic tracing, added logging for flaky test

topic/topictypes/topictypes.go, topic/topicwriter/topicwriter_test.go
=> small doc fixes

CHANGELOG.md, internal/topic/topicwriterinternal/writer_reconnector.go
=> Allow send zero messages

CHANGELOG.md, go.mod, go.sum, internal/clone/slice.go, internal/grpcwrapper/rawscheme/entry.go, internal/grpcwrapper/rawtopic/alter_topic.go, internal/grpcwrapper/rawtopic/controlplane_types.go, internal/grpcwrapper/rawtopic/create_topic.go, internal/grpcwrapper/rawtopic/describe_topic.go, internal/table/session.go, internal/table/session_test.go, internal/topic/topicclientinternal/client.go, internal/topic/topicreaderinternal/reader.go, scheme/scheme.go, table/options/models.go, topic/cdc_reader_e2e_test.go, topic/client.go, topic/client_e2e_test.go, topic/topic_read_writer_e2e_test.go, topic/topicoptions/topicoptions_alter.go, topic/topicoptions/topicoptions_create.go, topic/topictypes/topictypes.go
=> Topic control plane

CHANGELOG.md, internal/grpcwrapper/rawtopic/rawtopicreader/rawtopicreader.go, internal/grpcwrapper/rawtopic/rawtopicwriter/streamwriter.go, internal/topic/topicwriterinternal/encoders.go, internal/topic/topicwriterinternal/queue.go, internal/xcontext/cancel_with_error.go, internal/xcontext/cancel_with_error_test.go, internal/xerrors/ydb.go
=> Fixes for topic: reconnect problem, fix panic on queue limiter

CHANGELOG.md, topic/topictypes/topictypes.go, topic/topictypes/topictypes_test.go
=> [topic] add missing RetentionPeriod on describe

topic/README.md
=> add topic readme

internal/topic/topicwriterinternal/writer_reconnector_test.go, internal/topic/topicwriterinternal/writer_reconnector_unsafe_test.go
=> workaround for flaky test TestWriterReconnector_Write_QueueLimit

topic/client_e2e_test.go, topic/example_test.go
=> add examples

CHANGELOG.md, connection.go, internal/balancer/balancer.go, internal/balancer/local_dc_test.go, internal/conn/pool.go
=> * Added retries to initial discovering

CHANGELOG.md, go.mod, internal/table/scanner/scanner.go, table/table_regress_test.go
=> Fixed bug from scan unexpected column

internal/balancer/local_dc_test.go, internal/xsync/mutex_test.go
Some test runned many times with fixed run times. It can timeout fail on slow system (github action runner)
Change the tests from fixed run number to time limit of tests repeat.
=> change many times tests limit from fixed run test number to time limit

CHANGELOG.md, table/options/options.go
=> * Added `table/options.WithDataColumns` for supporting covering indexes

internal/xsync/event_broadcast_test.go
Wait a second while complete background all goroutines
Wait a second while complete some background goroutines
=> Improve test code for SubscribeAndEventsInRace

internal/topic/topicreaderinternal/stream_reader_impl_test.go, internal/xtest/manytimes.go
Race between commit message wait and close timeout
explicit wait commit message
decrease batch pause for tests to zero
=> Improve stable of code test TestTopicStreamReaderImpl_CommitStolen

CHANGELOG.md, balancers/config.go, balancers/config_test.go, internal/xsql/dsn.go
=> * Supported `balancer` query string parameter in DSN

CHANGELOG.md, internal/topic/topicwriterinternal/message.go, internal/topic/topicwriterinternal/writer_options.go, internal/topic/topicwriterinternal/writer_reconnector.go, topic/topicoptions/topicoptions_writer.go, topic/topicwriter/topicwriter.go
… unavailable on server side yet.
Removed message level partitioning from experimental topic API. It is unavailable on server side yet.
=> Removed message level partitioning from experimental topic API

CHANGELOG.md, sugar/table_exists.go
=> * Added `sugar.IsTableExists()` helper for check existence of table

CHANGELOG.md, internal/table/session.go, internal/table/ttl.go, table/example_test.go, table/options/models.go, table/options/models_test.go
=> * Added fluent modifiers for `options.TimeToLiveSettings`

CHANGELOG.md, topic/README.md
=> Remove a mistake

internal/table/client.go
=> fix duplicate table.do tracing

CHANGELOG.md, internal/table/session.go, internal/table/statement.go, internal/table/transaction.go, table/example_test.go, table/table.go, table/table_e2e_test.go
=> * Supported `table.Transaction.WithCommit()` method for execute query and auto-commit after

CHANGELOG.md, internal/topic/topicwriterinternal/writer_options.go, topic/topicoptions/topicoptions_reader.go, topic/topicoptions/topicoptions_writer.go
Add public option for interval of update auth token in topic api.
=> add update token interval options for topic

codecov.yml
=> added codecov.yml

CHANGELOG.md, internal/conn/middleware.go, internal/table/session.go, internal/xsql/badconn/badconn_go1.18.go, internal/xsql/conn.go, trace/sql.go, trace/sql_gtrace.go, trace/table.go
=> Last usage

.golangci.yml, CHANGELOG.md, internal/cmd/gtrace/writer.go, internal/table/session.go, internal/table/statement.go, internal/table/transaction.go, internal/table/transaction_test.go, log/table.go, table/example_test.go, table/options/options.go, table/table.go, table/table_e2e_test.go, trace/table.go, trace/table_gtrace.go
=> Reverted tx.WithCommit() and added options.WithCommit() option of ExecuteDataQuery

CHANGELOG.md, trace/details.go
=> * Added `trace.Details.Details()` method for use external detailer

CHANGELOG.md, internal/xsql/connector.go, sql.go
=> * Added `ydb.WithDisableServerBalancer()` database/sql connector option

CHANGELOG.md, internal/balancer/balancer.go, internal/conn/conn.go, internal/conn/context.go
=> * Fixed wrapping error in `internal/balancer/Balancer.wrapCall()`

CHANGELOG.md, internal/table/session.go, internal/xsql/conn.go, internal/xsql/connector.go, internal/xsql/errors.go, internal/xsql/rows.go, internal/xsql/stmt.go, internal/xsql/tx.go, internal/xsql/unwrap.go, internal/xsql/unwrap_go1.18.go, options.go, table/table_e2e_test.go
=> * Fixed closing of database/sql connection (aka `YDB` session)

internal/topic/topicreaderinternal/stream_reader_impl.go, topic/client_e2e_test.go, topic/topic_read_writer_e2e_test.go
=> Issue 487 reader stop after update token

topic/topic_stress_test.go
=> fix wait timeout for ci env

CHANGELOG.md, internal/balancer/balancer.go, internal/balancer/local_dc_test.go
=> * Fixed retry of cluster discovery on initialization

CHANGELOG.md, internal/table/session.go, table/example_test.go, table/options/models.go, table/options/options.go, table/table_e2e_test.go
=> Fix index type

CHANGELOG.md, internal/scheme/helpers/check_exists.go, internal/scheme/helpers/check_exists_test.go
Issue Number: [#542](https://github.com/ydb-platform/ydb-go-sdk/issues/542#issue-1565538359)
=> Fixed recursive bug

internal/wait/wait.go
This reverts commit b69b5d9343d5d386e2280bb627ac1966015be459.
=> Revert "corner cases for wait.Wait"

.github/workflows/breaking.yml, .github/workflows/check-codegen.yml, .github/workflows/lint.yml, .github/workflows/tests.yml
Run tests on go 1.16, 1.18, 1.19
Run tests on go 1.16, 1.19, 1.20
=> upgrade latest version to go 1.20

CHANGELOG.md, internal/xerrors/errorf.go, internal/xerrors/errorf_test.go, internal/xerrors/issues.go, retry/retry.go
=> fixed xerrors.MultiErrorf -> xerrors.Errorf

.github/workflows/tests.yml
=> integration tests for secure and insecure connections

.github/workflows/breaking.yml, .github/workflows/changelog.yml, .github/workflows/check-codegen.yml, .github/workflows/lint.yml, .github/workflows/tests.yml
=> update requirment actions

connection.go
=> fix pool initialization after config applying

internal/conn/conn.go
=> fixed grpc dial - make grpc dial options on real dial stage

.github/scripts/wait-ydb-container.sh, .github/workflows/tests.yml, CHANGELOG.md, config/config.go, connection.go, internal/dsn/dsn.go, tests/monitoring_test.go, tests/static_credentials_test.go
=> remove skipping tests for testing with latest docker image

CHANGELOG.md, connection.go, internal/balancer/balancer.go, internal/balancer/local_dc_test.go, log/driver.go, trace/driver.go, trace/driver_gtrace.go
=> * Added `trace.Driver.{OnBalancerDialEntrypoint,OnBalancerClusterDiscoveryAttempt}` trace events

CHANGELOG.md, internal/table/scanner/result.go, internal/xsql/badconn/badconn_go1.18.go, internal/xsql/conn.go, internal/xsql/rows.go, internal/xsql/tx.go, tests/database_sql_regression_test.go, tests/table_test.go
* Added test for `database/sql` scan-query
-
-
-
=> * Added wrapping of errors from unary and stream results

connection_test.go, example_test.go
=> refactoring of exaamples

.github/workflows/tests.yml, tests/README.md, tests/integration/README.md, tests/integration/connection_test.go, tests/integration/database_sql_regression_test.go, tests/integration/database_sql_test.go, tests/integration/discovery_test.go, tests/integration/monitoring_test.go, tests/integration/ratelimiter_test.go, tests/integration/scripting_test.go, tests/integration/static_credentials_test.go, tests/integration/table_regression_test.go, tests/integration/table_test.go, tests/integration/topic_cdc_reader_test.go, tests/integration/topic_client_test.go, tests/integration/topic_grpc_stopper_helper_test.go, tests/integration/topic_read_writer_test.go, tests/integration/topic_stress_test.go, tests/slo/database/sql/README.md, tests/slo/native/README.md
=> refactored integration tests + add slo workloads paths

tests/integration/database_sql_regression_test.go
=> fix TestRegressionKikimr17104

internal/value/type.go, table/types/types.go, table/types/types_test.go
=> Added internal methods for optional type for casts some type to optional

README.md, SQL.md, SQL_MIGRATION_v2_v3.md, coordination/example_test.go, discovery/example_test.go, example_test.go, meta/example_test.go, ratelimiter/example_test.go, scheme/example_test.go, scripting/example_test.go, table/example_test.go, topic/README.md
=> fixed grpcs connection in examples to grpc connection

internal/xtest/waiters.go, tests/integration/topic_stress_test.go
1. Fixed parallel topic counter (10)
2. Wait finish process fixed time
1. Limit parallels by GOMAXPROCS
2. Check hung as no progress instead of check target condition only
=> Fix flacky TestReadersWritersStress

CHANGELOG.md, internal/conn/conn.go, log/driver.go, trace/driver.go, trace/driver_gtrace.go
=> Deprecated `trace.Driver.OnConnTake` event callback + Added `trace.Driver.OnConnDial` event callback

example_test.go, internal/xsql/conn.go, internal/xsql/conn_test.go, internal/xsql/dsn.go, tests/integration/database_sql_numeric_args_test.go, tests/integration/database_sql_positional_args_test.go
=> fixed integration tests and examples with dsn args

internal/dsn/dsn.go, internal/dsn/dsn_test.go, internal/xerrors/xerrors.go, internal/xsql/dsn.go, internal/xsql/dsn_test.go, options.go, sql.go, sugar/dsn_test.go
=> fixed parsing of dsn and create database/sql driver with sql.Open

tests/integration/database_sql_numeric_args_test.go, tests/integration/database_sql_positional_args_test.go, tests/integration/database_sql_regression_test.go, tests/integration/database_sql_test.go
=> fix integration tests

sugar/path.go, tests/integration/database_sql_numeric_args_test.go, tests/integration/database_sql_positional_args_test.go, tests/integration/database_sql_test.go, tests/integration/sugar_make_remove_recursive_test.go, tests/integration/table_test.go
=> fixed sugar.{Make,Remove}Recursive + added integration test

CHANGELOG.md, connection.go, example_test.go, internal/xsql/conn.go, internal/xsql/connector.go, internal/xsql/unwrap.go, options.go, sql.go, sql_unwrap.go, sql_unwrap_go1.18.go, sugar/path.go, tests/integration/connection_test.go, tests/integration/database_sql_regression_test.go, tests/integration/table_regression_test.go, tests/integration/table_test.go, tests/integration/topic_cdc_reader_test.go, tests/integration/topic_client_test.go, tests/integration/topic_read_writer_test.go, tests/integration/topic_stress_test.go, topic/topicoptions/topicoptions_reader_example_test.go, topic/topicoptions/topicoptions_writer_example_test.go, with.go, with_test.go
=> * Changed result type in `ydb.Open()` from `ydb.Connection` interface type to `*ydb.Driver`

.github/workflows/tests.yml
=> cache compiled dependencies for improve compile speed, especially for windows

CHANGELOG.md, examples/topic/topicwriter/topicwriter.go, internal/topic/topicclientinternal/client.go, internal/topic/topicwriterinternal/writer_options.go, internal/topic/topicwriterinternal/writer_reconnector.go, tests/integration/topic_read_writer_test.go, tests/integration/topic_stress_test.go, topic/client.go, topic/topicoptions/topicoptions_writer.go, topic/topicoptions/topicoptions_writer_example_test.go, topic/topicwriter/topicwriter_test.go
remove WithMessageGroupID (because unsupported now).
-
-
-
=> make producerID on start topic writer is optional

tests/integration/topic_stress_test.go
=> Longer time for wait progress

.golangci.yml, CHANGELOG.md, connection.go, connection_test.go, example_test.go, options.go, sql.go, sugar/path.go, tests/integration/connection_test.go, tests/integration/table_test.go, with.go, with_test.go
Change connection API, see in changelogs.
=> Connection to driver changes

CHANGELOG.md, internal/xsql/conn.go, internal/xsql/tx.go
Issue Number: [#630](https://github.com/ydb-platform/ydb-go-sdk/issues/630)
=> Remove `driver.ResultNoRows` in `internal/xsql`

CHANGELOG.md, sugar/path.go, tests/integration/database_sql_test.go, tests/integration/sugar_make_remove_recursive_test.go, tests/integration/table_test.go
=> Remove recursive topic

CHANGELOG.md, sugar/path.go
=> Remove topic in sugar.RemoveRecursive

CHANGELOG.md, internal/meta/version.go
=> merge-commit from release-3.42 into master

internal/conn/conn.go
=> fix naming / revert modificationMark field about dirty or can retry

tests/integration/database_sql_scheme_test.go
Issue Number: [#636](https://github.com/ydb-platform/ydb-go-sdk/issues/636)
=> integration test for issue #636

CHANGELOG.md, internal/scheme/client.go, internal/scheme/helpers/check_exists.go, internal/xsql/conn.go, internal/xsql/conn_test.go, internal/xsql/connector.go, internal/xsql/tx.go, scheme/scheme.go, sql.go, tests/integration/database_sql_scheme_test.go
=> Databasesql test

tests/integration/sugar_make_remove_recursive_test.go
=> Simplify sugar test text

CHANGELOG.md, internal/xsql/conn.go
=> Fixed extended API

CHANGELOG.md, internal/xerrors/xerrors.go
=> Fix xerrors is

CHANGELOG.md, connection_test.go, internal/meta/version.go, tests/integration/table_test.go
=> Merge 3.43

CHANGELOG.md, internal/xerrors/operation.go, internal/xerrors/operation_test.go, internal/xerrors/stacktrace_test.go, internal/xerrors/transport.go, internal/xerrors/transport_test.go, internal/xsql/badconn/badconn.go, internal/xsql/badconn/badconn_go1.18.go, internal/xsql/rows.go, retry/errors.go
=> * Added grpc and operation codes to errors string description

CHANGELOG.md, config/defaults.go, internal/conn/conn.go, internal/conn/grpc_client_stream.go, internal/xerrors/transport.go, internal/xsql/bind/args_type.go, internal/xsql/bind/bind.go, internal/xsql/mode.go, tests/integration/database_sql_regression_test.go
* Fixed `internal/xerrors.Transport` error wrapping for case when given error is not transport error
-
-
-
=> * WithBlock()

CHANGELOG.md, SQL.md, connection.go, example_test.go, internal/xsql/bind/bind.go, internal/xsql/bind/bind_test.go, internal/xsql/bind/helpers.go, internal/xsql/bind/helpers_test.go, sql.go
* Added query enrichment part to `SQL.md`
* Added examples for query enrichment
-
-
-
=> * Added `ydb.MustOpen` and `ydb.MustConnector` helpers

.github/workflows/tests.yml
=> switch ydb docker image from 22-5 to 23-1

.github/workflows/tests.yml
=> changed fixed ydb version to matrix

CHANGELOG.md, options.go, tests/integration/helpers_test.go, tests/integration/table_bulk_upsert_example_test.go
=> * Added `ydb.WithCompression()` option

examples/go.mod, examples/serverless/healthcheck/README.md, examples/serverless/url_shortener/README.md
=> refactored examples

.github/workflows/slo.yml, tests/slo/Dockerfile, tests/slo/go.mod, tests/slo/native/main.go
=> Empty slo config

CHANGELOG.md, internal/table/client.go, internal/table/client_test.go, internal/table/errors.go, testutil/session.go
=> * Fixed bug with put session from unknown node

CHANGELOG.md, internal/conn/conn.go, internal/conn/grpc_client_stream.go, internal/credentials/static.go, internal/discovery/discovery.go, internal/xerrors/issues.go, internal/xerrors/operation.go, internal/xerrors/operation_test.go
=> * Added address of node to operation error description as optional

.github/workflows/breaking.yml
=> gorelease command

.github/workflows/slo.yml, tests/slo/Dockerfile, tests/slo/database/sql/main.go
=> Slo workflow update

.github/workflows/slo.yml
SLO test is broken now
Issue Number: https://github.com/ydb-platform/slo-tests/pull/26
=> feat: add language_id support for slo workflow

internal/bind/auto_declare.go, internal/bind/bind.go, internal/bind/errors.go, internal/bind/numeric_args.go, internal/bind/numeric_args_test.go, internal/bind/params.go, internal/bind/params_test.go, internal/bind/positional_args.go, internal/bind/positional_args_test.go, internal/bind/sql_lexer.go, internal/bind/table_path_prefix.go, internal/xsql/connector.go, internal/xsql/context.go, internal/xsql/dsn.go, internal/xsql/dsn_test.go, query_bind_test.go, sql.go, sugar/params.go, sugar/params_go1.18.go, sugar/params_go1.18_test.go, testutil/query_bind.go
=> refactoring

internal/bind/auto_declare.go, internal/bind/bind.go, internal/bind/bind_test.go, internal/bind/numeric_args.go, internal/bind/positional_args.go, internal/bind/table_path_prefix.go, internal/xsql/connector.go, internal/xsql/context.go, internal/xsql/dsn.go, internal/xsql/dsn_test.go, sql.go, testutil/query_bind.go
=> sort bindings

internal/bind/positional_args.go, query_bind_test.go
=> ignore ?? on positional args binder

sugar/path.go
sugar.RemoveRecursive() do nothing if path is database root
=> fix: sugar.RemoveRecursive do nothing if path is database root

tests/slo/internal/config/config.go
SLO workload native not working
=> fix: slo workload native

tests/slo/internal/workers/read.go, tests/slo/internal/workers/write.go
workers logging even nil errors (no error)
- better latency for read/write (about 20ms lower)
- no more messages for nil errors in log
=> fix: logging nil errors in slo native workers

CHANGELOG.md, config/defaults.go
=> removed WithBlock() from defaults

.github/workflows/breaking.yml, .gitignore
=> fix breakinig action

CHANGELOG.md, connection.go, internal/balancer/balancer.go, internal/table/client.go, internal/table/client_test.go, internal/table/session_test.go
=> fix bug with no put session before second discovery

connection.go, internal/table/client.go, internal/table/client_test.go, internal/table/session_test.go
=> fix bugfix

.github/workflows/slo.yml, tests/slo/database/sql/README.md, tests/slo/database/sql/main.go, tests/slo/database/sql/storage.go, tests/slo/internal/generator/generator.go, tests/slo/internal/generator/row.go, tests/slo/native/storage.go
Issue Number: #568 
SLO workload for database/sql driver
=> SLO workload database/sql

examples/go.mod, examples/go.sum
=> dependencies: update gorm-driver

.github/workflows/tests.yml
=> fix docker image tags

.github/workflows/lint.yml, .golangci.yml, examples/basic/database_sql/data.go, examples/basic/database_sql/main.go, examples/basic/database_sql/series.go, examples/basic/gorm/main.go, examples/basic/gorm/models.go, examples/basic/native/series.go, examples/ddl/ddl.go, examples/describe/main.go, examples/read_table/orders.go, examples/serverless/healthcheck/service.go, examples/serverless/url_shortener/main.go, examples/serverless/url_shortener/service.go, examples/topic/cdc-cache-bus-freeseats/database.go, examples/topic/cdc-cache-bus-freeseats/main.go, examples/topic/cdc-cache-bus-freeseats/webserver.go, examples/topic/cdc-fill-and-read/cdc-reader.go, examples/topic/cdc-fill-and-read/main.go, examples/topic/cdc-fill-and-read/tables.go, examples/topic/topicreader/stubs.go, examples/topic/topicreader/topicreader_advanced.go, examples/topic/topicreader/topicreader_show.go, examples/topic/topicreader/topicreader_trace.go, examples/topic/topicwriter/topicwriter.go, examples/ttl/series.go
Issue Number: #697 
- add linters for examples
- fix linter problems in examples
=> feat: use golangci-lint for check examples code

.github/workflows/tests.yml
=> build(deps): bump codecov-action v2 to v3

.github/workflows/slo.yml
=> fix: slo parallel collision

examples/basic/gorm/models.go
=> chore(examples): remove NOT NULL non-PrimaryKey columns from basic/gorm

.github/workflows/examples.yml, .github/workflows/tests.yml
=> ci: add ydb 23.2 to integration tests

.github/workflows/slo.yml
=> ci: add label to skip slo tests

.github/workflows/examples.yml, examples/basic/database_sql/series.go
=> fix examples CI

.github/workflows/slo.yml, tests/slo/Dockerfile, tests/slo/database/sql/main.go, tests/slo/database/sql/storage.go, tests/slo/gorm/main.go, tests/slo/internal/metrics/metrics.go, tests/slo/internal/workers/workers.go, tests/slo/native/main.go, tests/slo/native/storage.go
=> test(slo): update to js-version

CHANGELOG.md, internal/balancer/balancer.go
=> * Disabled check of node exists with `balancers.SingleConn`

CHANGELOG.md, scheme/scheme.go
=> * Added `scheme.Entry.IsColumnTable()` helper

internal/conn/pool.go
Connections are closing sequentially
Issue Number: #759 
Connections are closing parallel
=> made closing connections parallel

internal/xsql/rows.go
Issue Number: [#761](https://github.com/ydb-platform/ydb-go-sdk/issues/761#issue-1741075223)
=> bugfix: fix single row

.github/workflows/slo.yml
=> enable SLO check only on PRs

.github/workflows/slo.yml, tests/slo/internal/generator/row.go, tests/slo/xorm/storage.go
=> test(slo): xorm fixes

examples/basic/database_sql/series.go
=> refactor: remove not from dropTableIfExists function

CHANGELOG.md, internal/scheme/helpers/check_exists.go, internal/scheme/helpers/check_exists_test.go, internal/xsql/conn.go, scheme/scheme_test.go, sugar/check_exists.go
=> * Added `sugar.Is{Entry,ColumnTable}Exists` helper

CHANGELOG.md, table/types/cast.go, table/types/cast_test.go
=> * Added `table/types.IsOptional()` helper

internal/balancer/balancer.go
=> Added details to error from initial discovery

internal/stack/record.go, internal/stack/record_test.go, internal/xcontext/context_error.go, internal/xcontext/context_with_timeout.go, internal/xerrors/stacktrace.go, internal/xerrors/transport.go, retry/sql_test.go
=> Added internal package stack

internal/xsql/rows.go, tests/integration/database_sql_get_column_type_test.go
=> feat: implement RowsColumnTypeNullable interface for xsql rows

internal/topic/topicreaderinternal/message.go
=> Add context, topic, partition id to message builder

tests/slo/README.md, tests/slo/internal/metrics/metrics.go
=> Fix SLO latencies + README

SQL.md
=> fix bindings readme

retry/retry.go, tests/integration/table_data_query_with_compression_test.go, tests/integration/table_scan_error_test.go, tests/integration/table_scan_query_with_compression_test.go
Errors has not stacktrace and there is not enough information for debug.
Errors has stacktrace and additional information (count of attempts).
=> described retried errors

.github/workflows/tests.yml, CHANGELOG.md, sugar/path.go, tests/integration/sugar_make_remove_recursive_test.go
=> * Fixed `sugar.RemoveRecursive()` for column table type

.github/workflows/tests.yml, internal/table/session.go, table/options/options.go
=> Read table options

CHANGELOG.md, internal/table/scanner/scanner.go, internal/table/session.go, internal/table/statement.go, internal/xsql/connector.go, table/options/options.go, table/result/errors.go, tests/integration/helpers_test.go, tests/integration/table_truncated_err_test.go
=> `table.options.WithIgnoreTruncated` + `table.result.ErrTruncated`

CHANGELOG.md, internal/conn/conn.go, internal/conn/error.go, internal/conn/error_test.go, internal/conn/grpc_client_stream.go
=> add node info to error

CHANGELOG.md, internal/table/retry.go, internal/xerrors/issues.go, retry/sql.go
=> * Added checking condition for `tx.Rollback()` in `retry.DoTx`

CHANGELOG.md, table/options/options.go
=> Added `table/options.ReadFromSnapshot(bool)` option for `session.StreamReadTable()`

CHANGELOG.md, internal/xstring/convert.go, internal/xstring/convert_go1.21.go
=> fix reflect.{String,Slice}Header in go1.21

internal/background/worker_test.go, internal/conn/conn.go, internal/table/client_test.go, internal/table/scanner/result.go, internal/table/session.go, internal/table/transaction.go, internal/topic/topicreaderinternal/batcher_test.go, internal/topic/topicreaderinternal/committer_test.go, internal/topic/topicreaderinternal/partition_session.go, internal/topic/topicreaderinternal/stream_reader_impl.go, internal/topic/topicreaderinternal/stream_reader_impl_test.go, internal/topic/topicwriterinternal/queue_test.go, internal/xatomic/type.go, internal/xatomic/type_go1.19.go, internal/xsql/conn.go, internal/xsync/event_broadcast_test.go, tests/integration/database_sql_test.go, tests/integration/table_test.go, tests/integration/topic_partitions_balanced_test.go, tests/integration/topic_stress_test.go, topic/topicreader/reader.go, with.go
=> replace all atomic operations for atomic variables

internal/topic/topicreaderinternal/stream_reader_impl_test.go
=> Add test about free buffer after stop partition

internal/table/config/config.go, options.go
=> fix comments

tests/integration/database_sql_test.go
=> upgrade test

internal/conn/conn.go, internal/conn/error.go, internal/conn/error_test.go, internal/conn/grpc_client_stream.go
=> fix error message

CHANGELOG.md, internal/table/errors.go, internal/table/session.go, internal/table/session_test.go, table/example_test.go, table/options/options.go, table/table.go, tests/integration/table_copy_tables_test.go
=> * Added `table.Session.CopyTables` method

.github/workflows/tests.yml, tests/integration/database_sql_static_credentials_test.go, tests/integration/kv_test.go, tests/integration/static_credentials_test.go
=> 23.3 integration tests

CHANGELOG.md, examples/topic/topicreader/topicreader_advanced.go, examples/topic/topicreader/topicreader_show.go, internal/grpcwrapper/rawtopic/rawtopiccommon/codec.go, internal/topic/topicclientinternal/client.go, internal/topic/topicreaderinternal/batch.go, internal/topic/topicreaderinternal/commit_range.go, internal/topic/topicreaderinternal/committer.go, internal/topic/topicreaderinternal/decoders.go, internal/topic/topicreaderinternal/message.go, internal/topic/topicreaderinternal/public_callbacks.go, internal/topic/topicreaderinternal/reader.go, topic/client.go, topic/topicoptions/topicoptions_alter.go, topic/topicoptions/topicoptions_create.go, topic/topicoptions/topicoptions_describe.go, topic/topicoptions/topicoptions_drop.go, topic/topicoptions/topicoptions_reader.go, topic/topicoptions/topicoptions_writer.go, topic/topicreader/batch_options.go, topic/topicreader/errors.go, topic/topicreader/reader.go, topic/topicsugar/topicreader.go, topic/topictypes/topictypes.go, topic/topicwriter/topicwriter.go, trace/topic.go
remove a lot of expirement comments, deprecate some options, rename some options (old name was deprecated).
Doesn't remove anything now.
=> remove a lot of expirements comments.

internal/xsql/conn.go, internal/xsql/errors.go, tests/integration/database_sql_regression_test.go, tests/integration/tx_test.go
=> added TestNoEffectsIfForgetCommitTx

tests/integration/helpers_test.go, tests/integration/table_cross_join_test.go
=> added cross join test + upgraded test helpers

CHANGELOG.md, internal/scripting/client.go, internal/table/scanner/result.go, internal/table/scanner/result_test.go, internal/table/session.go, internal/xerrors/join.go, tests/integration/table_long_stream_test.go, tests/integration/table_scan_error_test.go
=> * Added receiving first result set on construct `internal/table/scanner.NewStream()`

CHANGELOG.md, SQL.md, example_test.go, examples/basic/database_sql/series.go, internal/table/client.go, internal/table/retry.go, internal/table/retry_test.go, metrics/table.go, retry/retry.go, retry/sql.go, retry/sql_test.go, table/table.go, tests/integration/database_sql_containers_test.go, tests/integration/database_sql_get_column_type_test.go, tests/integration/database_sql_get_columns_test.go, tests/integration/database_sql_get_index_columns_test.go, tests/integration/database_sql_get_indexes_test.go, tests/integration/database_sql_get_primary_keys_test.go, tests/integration/database_sql_get_tables_test.go, tests/integration/database_sql_is_column_exists_test.go, tests/integration/database_sql_is_primary_key_test.go, tests/integration/database_sql_is_table_exists_test.go, tests/integration/database_sql_regression_test.go, tests/integration/database_sql_test.go, tests/integration/table_truncated_err_test.go, tests/slo/database/sql/storage.go, tests/slo/gorm/storage.go, tests/slo/xorm/storage.go, trace/table.go, trace/table_gtrace.go
=> refactoring of retry options for `retry.Retry`, `retry.Do`, `retry.DoTx`, `table.Do`, `table.DoTx`

connection.go, with.go
=> rename of Driver variable name

internal/stack/record.go, internal/stack/record_test.go, internal/table/retry.go
=> refactored `internal/stack`

metrics/error_brief_test.go
=> fix TestErrorBrief

internal/xsql/badconn/badconn_go1.18_test.go, internal/xsql/conn.go, internal/xsql/errors.go, internal/xsql/isolation/isolation.go, internal/xsql/rows.go, internal/xsql/stmt.go, internal/xsql/tx.go
=> xsql fixes

internal/balancer/balancer.go, internal/repeater/repeater.go
=> added repeater init event

retry/retry.go, retry/sql.go
=> finalErr in retry

CHANGELOG.md, metrics/sql.go
=> * Fixed inconsistent labels in `metrics`

internal/table/retry.go, internal/xcontext/retry_call.go, retry/retry.go, retry/sql.go, trace/retry.go
=> move retry call detect into xcontext package

balancers/balancers.go, balancers/balancers_test.go, balancers/config.go, balancers/config_test.go, internal/balancer/balancer.go, internal/balancer/config/routerconfig.go, internal/balancer/connections_state.go, internal/balancer/connections_state_test.go, trace/driver.go, trace/driver_gtrace.go
=> balancer config name

internal/xsql/conn.go, internal/xsql/stmt.go, internal/xsql/tx.go, internal/xsql/tx_fake.go, log/sql.go, trace/sql.go, trace/sql_gtrace.go
=> refactoring of xsql

driver.go, internal/balancer/balancer.go, internal/conn/conn.go, internal/conn/pool.go, internal/discovery/discovery.go, internal/meta/meta.go, internal/repeater/repeater.go, internal/scheme/client.go, internal/scripting/client.go, internal/stack/function_id.go, internal/stack/record.go, internal/table/client.go, internal/table/retry.go, internal/table/retry_test.go, internal/table/session.go, internal/table/statement.go, internal/table/transaction.go, internal/xresolver/xresolver.go, internal/xsql/conn.go, internal/xsql/connector.go, internal/xsql/stmt.go, internal/xsql/tx.go, internal/xsql/tx_fake.go, retry/retry.go, retry/sql.go, trace/driver.go, trace/driver_gtrace.go, with.go
=> stack.FunctionID fix for codegen in the future

.golangci.yml, retry/sql_test.go
=> sqlclosecheck enabled

.golangci.yml, examples/serverless/healthcheck/service.go
=> bodyclose enabled

.golangci.yml, internal/cmd/gtrace/writer.go
=> deadcode enabled

.golangci.yml, balancers/config_test.go
=> gosec enabled

.golangci.yml, examples/serverless/healthcheck/service.go
=> noctx enabled

.golangci.yml, tests/slo/internal/generator/row.go
=> tagalign enabled

.golangci.yml, examples/topic/topicreader/topicreader_simple.go
=> tagliatelle enabled

.golangci.yml
=> varcheck enabled

.golangci.yml, examples/auth/access_token_credentials/main.go, examples/auth/anonymous_credentials/main.go, examples/auth/metadata_credentials/main.go, examples/auth/service_account_credentials/main.go, examples/auth/static_credentials/main.go, examples/ddl/main.go, examples/decimal/main.go, examples/pagination/main.go, examples/read_table/main.go, examples/serverless/healthcheck/main.go, examples/serverless/url_shortener/main.go, examples/ttl/main.go, examples/ttl_readtable/main.go
=> gochecknoinits enabled

.golangci.yml, internal/topic/topicreaderinternal/decoders.go, topic/topicsugar/topicreader.go
=> enable dupword linter

.golangci.yml, CHANGELOG.md, internal/bind/numeric_args.go, internal/xstring/convert_bench_test.go, tests/slo/database/sql/storage.go, tests/slo/native/storage.go, topic/example_test.go
Enabled goconst linter.
Issue Number: #939
=> enabled goconst

.golangci.yml, internal/background/worker_test.go, internal/table/scanner/perfomance_test.go, internal/topic/retriable_error.go, internal/topic/topicwriterinternal/writer_reconnector.go, table/options/models.go
enabled wastedassign linter
Issue Number: #975 
-
-
-
=> enabled wastedassign

CHANGELOG.md, internal/xsql/rows.go, tests/integration/database_sql_ignore_placeholder_test.go
=> * Supported column name prefix `__discard_column_` for discard columns in result sets

.golangci.yml, CHANGELOG.md, internal/grpcwrapper/rawtopic/describe_topic.go, internal/grpcwrapper/rawydb/issues.go
=> enable nilerr linter

CHANGELOG.md, internal/version/version.go
=> Release v3.56.1

.golangci.yml
FIxed gomoddirectives linter
Issue Number: #944 
-
-
-
=> fixed gomoddirectives linter

.github/workflows/tests.yml
=> added ydb-24.1 to intergration tests

.github/workflows/check-codegen.yml
=> fix mockgen version in CI => check-codegen

CHANGELOG.md, internal/topic/topicreaderinternal/stream_reader_impl.go
return private error
return known public error
=> return ErrCommitToExpiredSession for commit to stopped partitions

params_builder.go
=> add experimental mark for params builder

connection.go
=> Experimental remark for query service

internal/query/errors.go, internal/query/scanner_named.go, internal/query/scanner_named_test.go
=> added implementation of named scanner

internal/cmd/gtrace/.gitignore, internal/cmd/gtrace/main.go
- remove binary from repository
- remove dependency to internal function from go runtime
- stop to support _goos_goarch tags detection in gtrace
=> Clean gtrace

internal/params/parameters.go, internal/params/set.go, internal/params/set_test.go
=> Set query params

.github/workflows/slo.yml, internal/value/value.go, tests/slo/Dockerfile, tests/slo/internal/generator/row.go, tests/slo/native/query/storage.go
Issue Number: #1093 #1084 
-
-
-
=> fixed slo and optional.castTo

.github/workflows/examples.yml, .github/workflows/slo.yml, .github/workflows/tests.yml, CONTRIBUTING.md, examples/basic/native/query/data.go, examples/basic/native/query/main.go, examples/basic/native/query/series.go, examples/basic/native/table/main.go, examples/basic/native/table/series.go, internal/params/list.go
=> basic example over query service + excluded from CI tests over YDB versions `22.5`, `23.1`, `23.2` + switched ydb docker image to `hub.docker.com`

internal/pool/pool.go, internal/pool/pool_test.go
=> add pool implementation

internal/query/transaction.go, internal/query/transaction_test.go, query/execute_options.go, tests/integration/query_execute_test.go
=> lazy transactions: query.WithCommit() option + tests

tests/slo/native/query/storage.go
=> fix SLO over query service client

.github/workflows/examples.yml, .github/workflows/tests.yml
=> fix run query service client on YDB 24.1 (feature flag `enable_prepared_ddl`)

internal/pool/pool.go, internal/query/client.go, internal/query/client_test.go, internal/query/execute_query.go, internal/query/result.go, internal/query/session.go, internal/query/transaction_test.go
=> some fixes of query service client

query/named.go, query/result.go, sugar/result.go, tests/integration/sugar_result_test.go, tests/slo/native/query/storage.go
=> added `sugar.Result` for iterate over `query.Result`

internal/params/list_test.go, internal/params/set.go, internal/params/set_test.go
=> tests for .addItems() + .addItems() for set

CHANGELOG.md, internal/query/client.go, internal/query/session.go, internal/query/session_status.go, log/query.go, metrics/query.go, metrics/traces.go, query/session.go, trace/query.go, trace/query_gtrace.go
* Added session create and delete events into `trace.Query`
* Moved public type `query.SessionStatus` into `internal/query` package
Issue Number: #1104 
-
-
-
=> * Added metrics over query service internals

CHANGELOG.md, internal/params/builder_test.go, internal/params/parameters.go, internal/params/pg.go, internal/pg/pgconst.go, internal/types/types.go, internal/types/types_test.go, internal/value/value.go, internal/value/value_test.go
=> Add PG type as parameter support

CHANGELOG.md, example_test.go, examples/basic/native/query/main.go, examples/basic/native/query/series.go, examples/go.mod, examples/go.sum, internal/params/builder_test.go, internal/params/dict.go, internal/params/dict_test.go, internal/params/list.go, internal/params/list_test.go, internal/params/optional.go, internal/params/optional_test.go, internal/params/parameters.go, internal/params/set.go, internal/params/set_test.go, query/example_test.go, tests/slo/native/query/storage.go
=> changed in `ydb.ParamsBuilder()` container type constructors from `List()...Build()` to `BeginList()...EndList()` (`Dict`, `Set`, `Optional`)

internal/query/client.go, internal/query/client_test.go, internal/query/result_set.go, internal/query/session.go, tests/integration/query_execute_test.go, tests/integration/query_tx_execute_test.go
=> added node check when session check alive

CHANGELOG.md, internal/stack/function_id_test.go, internal/stack/record.go
=> * Fixed function id stringification for generic type function calls

CHANGELOG.md, internal/query/execute_query.go, internal/query/execute_query_test.go, internal/query/result.go, internal/query/result_set.go, internal/query/result_set_test.go, internal/query/result_test.go, internal/query/row.go, internal/query/scanner/indexed.go, internal/query/scanner/named.go, internal/query/scanner/struct.go, internal/query/session.go, log/query.go, metrics/query.go, tests/slo/native/query/storage.go, trace/details.go, trace/details_test.go, trace/query.go, trace/query_gtrace.go
* Added `trace.Query.OnResult{New,NextPart,NextResultSet,Close}` events
* Added `trace.Query.OnRow{Scan,ScanNamed,ScanStruct}` events
Issue Number: #1100 
-
-
-
=> * Added `trace.Query.OnSessionBegin` event

CHANGELOG.md, internal/types/types.go, internal/types/types_test.go, internal/value/value.go, internal/value/value_test.go
=> improve pg type stringification

CHANGELOG.md, internal/params/parameters.go, internal/params/struct.go, internal/params/struct_test.go
=> Added `Struct` support for `ydb.ParamsBuilder()`

.github/workflows/breaking.yml, CHANGELOG.md, README.md, config/config.go, internal/conn/config.go, internal/conn/conn.go, internal/conn/pool.go, internal/topic/topicreaderinternal/batcher.go, internal/topic/topicreaderinternal/batcher_test.go, options.go, table/options/models.go, trace/driver.go, trace/driver_gtrace.go
=> Revert conns parking

tests/integration/discovery_test.go, tests/integration/helpers_test.go, tests/integration/query_execute_test.go, tests/integration/topic_grpc_stopper_helper_test.go
=> revert integration tests

CHANGELOG.md, internal/conn/conn.go, internal/conn/grpc_client_stream.go, internal/conn/last_usage.go, internal/conn/last_usage_test.go
=> added lastUsage locked time

internal/meta/meta.go
=> pid singletone

CHANGELOG.md, internal/cmd/gstack/main.go, internal/query/client.go
=> Fix gstack

internal/params/builder_test.go, internal/params/dict_test.go, internal/params/list_test.go, internal/params/optional_test.go, internal/params/pg_test.go, internal/params/set_test.go, internal/params/struct_test.go, internal/params/tuple_test.go, internal/xtest/to_json.go, internal/xtest/to_json_test.go
=> added xtest.ToJSON()

CHANGELOG.md, internal/coordination/client.go, internal/coordination/client_test.go, internal/coordination/session.go, log/coordination.go, tests/integration/coordination_test.go, trace/coordination.go, trace/coordination_gtrace.go
=> Coordination trace events

CHANGELOG.md, coordination/coordination.go, coordination/example_test.go, coordination/options/options.go, examples/coordination/lock/main.go, examples/coordination/workers/main.go, internal/coordination/client.go, internal/coordination/session.go, log/coordination.go, tests/integration/coordination_test.go, trace/coordination.go, trace/coordination_gtrace.go
=> * Renamed `db.Coordination().CreateSession()` to `db.Coordination().Session()` for compatibility with protos

CHANGELOG.md, internal/query/execute_query_test.go, internal/query/tx/control.go, query/session.go
=> * Changed default transaction control to `NoTx` for execute query through query service client

log/logger_test.go
=> fix flaky logger test

.golangci.yml, internal/balancer/balancer.go, internal/bind/numeric_args.go, internal/bind/params.go, internal/conn/conn.go, internal/scripting/client.go
=> Enable funlen linter

CHANGELOG.md, internal/params/variant.go, internal/params/variant_struct.go, internal/params/variant_struct_test.go
=> variant struct

CHANGELOG.md, internal/cmd/gstack/main.go, internal/stack/function_id_test.go
=> Add go with anonymous function case in gstack

CHANGELOG.md, internal/coordination/session.go, internal/table/client.go, internal/topic/topicreaderinternal/committer.go, internal/topic/topicreaderinternal/stream_reconnector.go, internal/topic/topicwriterinternal/writer_reconnector.go, internal/xsql/connector.go
=> Fixed timers leaks

internal/pool/pool.go
=> use errgroup for close internal/pool

.github/workflows/breaking.yml, .github/workflows/changelog.yml, .github/workflows/check-codegen.yml, .github/workflows/codeql-analysis.yml, .github/workflows/examples.yml, .github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/slo.yml, .github/workflows/tests.yml
=> updated actions checkout, setup-go, golangci-lint-action, codeql-actions and upload-artifact

CHANGELOG.md, examples/go.mod, examples/go.sum, go.mod, go.sum, retry/errors_data_test.go, tests/slo/go.mod, tests/slo/go.sum
=> * Added processing of `Ydb.StatusIds_EXTERNAL_ERROR` in `retry.Retry`

CHANGELOG.md, internal/conn/grpc_client_stream.go
Use local context variable instead of context pointer for tracing.
Issue Number: #1205
=> #1205: Fix data race in grpc_client_stream

CHANGELOG.md, internal/conn/conn.go, internal/conn/grpc_client_stream.go, internal/xcontext/cancels_quard.go, internal/xcontext/cancels_quard_test.go, internal/xtest/grpclogger.go, log/driver.go, metrics/driver.go, trace/details.go, trace/driver.go, trace/driver_gtrace.go
=> Trace stream finish

CHANGELOG.md, internal/credentials/oauth2_test.go
=> fixed OAuth2 test

internal/query/result.go, internal/query/session.go, internal/table/scanner/scanner.go
=> Enable funlen linter (part 3)

CHANGELOG.md, internal/background/worker.go, internal/topic/topicwriterinternal/writer_reconnector.go, internal/topic/topicwriterinternal/writer_reconnector_test.go
=> Fixed data race on close topic writer

CHANGELOG.md, internal/decimal/decimal.go, internal/decimal/decimal_test.go, tests/integration/unexpected_decimal_parse_test.go
implementation of decimal formatter was reverted to latest working version (3.66.0)
#1234 
-
-
-
=> Revert decimal to latest working version.

CHANGELOG.md, go.mod
=> retracted v3.67.1 because decimal stringification broken

internal/credentials/oauth2_test.go
=> fix OAuth2 credentials unit tests

.github/workflows/breaking.yml, .github/workflows/check-codegen.yml, .github/workflows/examples.yml, .github/workflows/lint.yml, .github/workflows/tests.yml, CHANGELOG.md, README.md, go.mod, go.sum, internal/pool/pool_test.go, internal/topic/topicreaderinternal/stream_reconnector.go, internal/xcontext/done.go, internal/xcontext/done_test.go, internal/xcontext/without_deadline.go, internal/xcontext/without_deadline_go1.20.go, internal/xsync/last_usage_guard.go, internal/xsync/last_usage_guard_start.go, internal/xsync/last_usage_guard_start_go1.20.go
=> * Downgraded minimal version of Go to 1.20

internal/conn/conn.go, internal/coordination/conversation/conversation.go, internal/credentials/static.go, internal/decimal/decimal.go, internal/topic/topicreaderinternal/stream_reader_impl.go, internal/topic/topicwriterinternal/writer_reconnector.go
=> Enable funlen linter (part 6)

internal/conn/conn.go, internal/coordination/session.go, internal/topic/topicwriterinternal/writer_reconnector.go, internal/xsql/conn.go
=> Enable funlen linter (part 7)

internal/table/client.go, internal/xsql/conn.go, sugar/path.go
=> Enable funlen linter (part 8) 

CHANGELOG.md, internal/query/result.go, internal/query/result_set.go, internal/query/result_set_test.go, query/result.go, sugar/query_test.go, tests/integration/query_tx_execute_test.go
=> * Added `query/ResultSet.{Columns,ColumnTypes}` methods for get column names and types from query result set

CHANGELOG.md, connection.go, driver.go
=> * Excluded `Query()` method from interface `ydb.Connection`. Method `Query()` remains accessible from `ydb.Driver`

CHANGELOG.md, internal/query/scanner/named.go, internal/query/scanner/named_test.go, query/result.go, retry/retry.go, retry/sql.go
=> Added `retry.DoWithResult` and `retry.DoTxWithResult`

CHANGELOG.md, query/transaction.go
=> * Changed `query.DefaultTxControl()` from `quury.SerializableReadWrite()` with commit to `query.NoTx()`

internal/table/client.go, internal/table/session.go
=> Enable funlen linter (part 9)

internal/value/cast.go, internal/value/cast_test.go, internal/value/errors.go
=> added test for internal/value.CastTo()

internal/query/options/retry.go, query/client.go
=> remove query.bothDoAndDoTxOption

internal/topic/topicreaderinternal/committer.go, internal/topic/topicreaderinternal/committer_test.go, internal/topic/topicreaderinternal/stream_reader_impl.go, internal/topic/topicwriterinternal/writer_single_stream.go
=> fix goroutine labels

internal/query/scanner/indexed_test.go, internal/query/scanner/named_test.go, internal/query/scanner/struct_test.go, internal/value/cast_test.go, internal/value/value.go
=> Add more tests for cast.

CHANGELOG.md, query/client.go, query/transaction.go
=> Added public types for `tx.Option` and `options.DoOption`

CHANGELOG.md, internal/query/execute_query_test.go, internal/query/session_test.go, internal/query/transaction.go, internal/query/tx/control.go, internal/query/tx/id.go, query/transaction.go
=> * Removed public `query.Identifier` interface for exclude any external implementations for use with YDB

CHANGELOG.md, internal/dsn/dsn.go, internal/dsn/dsn_test.go
=> * Allowed the use of DSN without specifying the protocol/scheme

CHANGELOG.md, internal/value/value.go, internal/value/value_test.go
=> fix cast int* to uint*

CHANGELOG.md, internal/query/scanner/indexed.go, internal/query/scanner/indexed_test.go, internal/query/scanner/named.go, internal/query/scanner/named_test.go, internal/query/scanner/struct.go, internal/query/scanner/struct_test.go, internal/value/errors.go, internal/value/value.go
=> added description to error message if scan failed

.golangci.yml, driver.go, dsn.go, internal/table/session.go, internal/value/value.go, metrics/driver.go, metrics/query.go, metrics/sql.go, metrics/table.go, query_bind_test.go, with_test.go
=> Enable funlen linter (part final)

CHANGELOG.md, balancers/balancers.go, internal/xslices/clone.go, internal/xslices/clone_1.20.go
=> PreferLocations is pure function now

CHANGELOG.md, internal/balancer/balancer.go, internal/query/client.go, internal/query/session.go, internal/table/client.go, internal/table/client_test.go, internal/table/errors.go, internal/table/session.go, testutil/driver.go
=> * Diabled check the node is available for query service session

CHANGELOG.md, internal/query/client.go, internal/query/config/config.go, tests/integration/query_execute_test.go
=> * Replaced internal query session pool by default to stub for exclude impact from internal/pool

internal/xstring/convert.go
=> Duplicated length check removed

tests/integration/sugar_unmarhall_result_set_test.go, tests/integration/table_tx_lazy_test.go
=> Fix panic when database is nil.

.github/workflows/tests.yml
Schedule run tests on master branch - for research flacky tests
=> schedule run tests

internal/xtest/logger.go, tests/integration/basic_example_native_test.go, tests/integration/connection_secure_test.go, tests/integration/connection_test.go, tests/integration/connection_with_compression_test.go, tests/integration/discovery_test.go, tests/integration/helpers_test.go, tests/integration/metrics_registry_test.go, tests/integration/ratelimiter_test.go, tests/integration/scripting_test.go, tests/integration/table_create_table_description_test.go, tests/integration/table_create_table_partitions_test.go, tests/integration/table_long_stream_test.go, tests/integration/table_multiple_result_sets_test.go, tests/integration/topic_read_writer_test.go
=> fix race between logger in tests

internal/topic/topicwriterinternal/writer_reconnector_test.go
=> fixed race on test logs

.github/workflows/tests.yml
=> Added codecov token from secrets

CHANGELOG.md, internal/query/errors.go, internal/query/result.go, internal/query/result_set.go, internal/query/result_set_range_test.go, internal/query/result_set_test.go, internal/query/result_test.go, query/result.go, sugar/query_test.go
=> Add `query.ResultSet.Index()` method

CHANGELOG.md, credentials/credentials.go, credentials/options.go, internal/credentials/oauth2.go, internal/credentials/oauth2_test.go, options.go
Load OAuth 2.0 token exchange credentials provider from config file
Implement RFC part in Go SDK: https://github.com/ydb-platform/ydb-rfc/blob/main/cli_oauth2_token_exchange.md
-
-
-
=> Load OAuth 2.0 token exchange credentials provider from config file

internal/conn/conn.go, internal/credentials/static.go, internal/decimal/decimal.go, internal/topic/topicwriterinternal/writer_reconnector.go
=> Fix linter

CHANGELOG.md, go.mod, go.sum
=> upgraded grpc dependency

internal/conn/grpc_client_stream.go
=> fixed the processing io.EOF on grpc streams

CHANGELOG.md, internal/params/builder_test.go, internal/params/parameters.go
=> Added `ydb.ParamsBuilder().Param(name).Any(value)` to add custom `types.Value`

tests/slo/internal/workers/metrics.go, tests/slo/internal/workers/read.go, tests/slo/internal/workers/workers.go, tests/slo/internal/workers/write.go
=> added timestamp to SLO log msgs

internal/table/client.go, internal/table/client_test.go, internal/xlist/list.go, internal/xlist/list_test.go
=> Added internal/xlist + switched internal/table.Client from container/list to internal/xlist

CHANGELOG.md, internal/topic/topicreaderinternal/reader.go, internal/topic/topicreaderinternal/stream_reader_impl.go
=> Improve topic reader config validation

internal/allocator/allocator.go, internal/xsync/pool.go, internal/xsync/pool_test.go
=> moved internal/allocator.Pool into internal/xsync package

internal/endpoint/diff.go, internal/endpoint/diff_test.go
=> Added endpoint.Diff

internal/xsync/map.go, internal/xsync/map_test.go
=> Added xsync.Map

internal/pool/pool.go, internal/pool/stats.go, internal/pool/trace.go, internal/query/client.go, query/client.go, query/stats.go, sugar/query_test.go
=> moved internal/pool/stats.Stats to internal/pool.Stats

driver.go, internal/xsync/once.go, internal/xsync/once_test.go
=> refactoring of xsync.OnceValue

internal/credentials/oauth2_test.go
=> fixed flaky TestOauth2TokenExchange

internal/balancer/balancer.go
=> switched internal/balancer.Balancer.connections_state from pointer to atomic.Pointer

internal/xslices/map.go, internal/xslices/map_test.go, internal/xslices/split.go, internal/xslices/split_test.go
=> added xslices.Map and xslices.Filter

CHANGELOG.md, balancers/balancers.go, balancers/balancers_test.go, balancers/config_test.go, internal/balancer/config/routerconfig.go, internal/balancer/connections_state.go, internal/balancer/connections_state_test.go
=> * Changed signature of filter func in balancers (replaced argument from `conn.Conn` type to `endpoint.Info`)

internal/credentials/oauth2_test.go
=> fixed TestErrorInHTTPRequest

CHANGELOG.md, internal/xslices/diff_test.go, internal/xslices/sort.go, internal/xslices/sort_copy.go, internal/xslices/sort_copy_test.go, internal/xslices/sort_go1.20.go, internal/xslices/sort_test.go
=> Fixed build for go1.20

CHANGELOG.md, internal/background/worker.go
=> remove quotas from background goroutine label

CHANGELOG.md, internal/xerrors/issues.go, internal/xerrors/retryable.go, internal/xerrors/transport.go
=> * Fixed `internal/xstrings.Buffer()` leak without call `buffer.Free()`

internal/xslices/filter.go, internal/xslices/filter_test.go, internal/xslices/split.go, internal/xslices/split_test.go
=> Added xslices.Split + refactored xslices.Filter

internal/balancer/state/errors.go, internal/balancer/state/state.go, internal/balancer/state/state_test.go
=> added internal/balancer/state package

internal/balancer/cluster/cluster.go, internal/balancer/cluster/cluster_test.go, internal/balancer/cluster/errors.go
=> renamed internal/balancer/state => internal/balancer/cluster

internal/xsync/map.go, internal/xsync/set.go, internal/xsync/set_test.go
=> added `internal/xsync.Map.Delete` + `internal/xsync.Set`

internal/credentials/oauth2_test.go
=> fix oauth test logs and remove many time execution

CHANGELOG.md, credentials/credentials.go, credentials/options.go, internal/credentials/oauth2.go, internal/credentials/oauth2_test.go, options.go
OAuth 2.0 token exchange. Allow multiple resource parameters
-
-
-
=> OAuth 2.0 token exchange. Allow multiple resource parameters

CHANGELOG.md, internal/query/options/execute.go, internal/query/transaction_test.go, tests/integration/helpers_test.go, tests/integration/query_tx_execute_test.go
=> Fixed respect to query.WithCommit() flag for tx.Execute in query service

CHANGELOG.md, examples/topic/topicreader/topicreader_handler.go, internal/topic/topiclistenerinternal/event_handler.go, internal/topic/topiclistenerinternal/event_handler_mock_test.go, internal/topic/topiclistenerinternal/stream_listener.go, internal/topic/topiclistenerinternal/stream_listener_test.go, tests/integration/topic_listener_test.go, topic/topiclistener/event_handler.go
=> Fix listener stop partition

internal/query/transaction.go, internal/query/tx/id.go
=> renamed tx.Parent to tx.ID

internal/grpcwrapper/rawtopic/rawtopiccommon/offset.go, internal/grpcwrapper/rawtopic/rawtopiccommon/rangeoffset.go, internal/grpcwrapper/rawtopic/rawtopicreader/messages.go, internal/topic/topiclistenerinternal/stream_listener.go, internal/topic/topiclistenerinternal/stream_listener_test.go, internal/topic/topicreadercommon/commit_range.go, internal/topic/topicreadercommon/commit_range_test.go, internal/topic/topicreadercommon/read_partition_session.go, internal/topic/topicreaderinternal/batcher_test.go, internal/topic/topicreaderinternal/committer.go, internal/topic/topicreaderinternal/committer_test.go, internal/topic/topicreaderinternal/public_callbacks.go, internal/topic/topicreaderinternal/stream_reader_impl_test.go
=> move offset to topiccommon

internal/query/client.go
=> fixed typo

.github/workflows/changelog.yml
=> skip changelog step instead on cancel/abort

internal/query/execute_query.go, internal/query/session.go, internal/query/transaction.go
=> make transaction internal public

CHANGELOG.md, internal/topic/topicreadercommon/message.go
=> fix builder methods return self

internal/topic/topicreadercommon/batch.go
=> fix internal name typo

internal/xtest/manytimes.go
=> Added early exit from `xtest.TestManyTimes()` on `-short` flag

internal/xerrors/join.go, internal/xerrors/join_test.go
=> Skipped nil errors in `xerrors.Join(errs)`

internal/table/client.go, internal/table/client_test.go, internal/table/errors.go, internal/table/retry_test.go, internal/table/session.go
=> added throwing create session error to result error from `internal/table.Client.internalPoolGet`

internal/query/transaction.go, internal/query/tx/control.go, internal/table/session.go, internal/table/session_test.go, internal/table/transaction.go, internal/tx/id.go, internal/xsql/conn.go, internal/xsql/tx.go, internal/xsql/tx_fake.go, query/transaction.go, table/table.go
=> moved `internal/query/tx.{Identifier,ID}` to new package `internal/tx`

.github/workflows/tests.yml, tests/integration/database_sql_static_credentials_test.go, tests/integration/static_credentials_test.go
=> run experimental tests on nightly ydb image

internal/topic/topicreadercommon/message.go
=> Add guarantee about memory release from the message content

CHANGELOG.md, internal/query/session.go, internal/query/session_test.go
=> * Fixed bug with nil pointer dereference on trace callback from `query.createSession`

tests/integration/helpers_test.go
=> remove usage deprecated methods of fixenv

tests/integration/helpers_test.go
=> Fix drop table in tests helper

internal/query/transaction.go
=> fixed possible multiply calls notifiers about stop transaction

CHANGELOG.md, internal/topic/topicreaderinternal/stream_reader_impl.go, log/topic.go, topic/topicreader/reader.go, trace/details.go, trace/topic.go, trace/topic_gtrace.go
=> Traces and logs for read messages within transaction

CHANGELOG.md, internal/conn/grpc_client_stream.go
We always get "context canceled" in traces when stream finished.
no error in treaces when stream finished.
-
-
-
=> Cancel context after tracing "finish" event

CHANGELOG.md, internal/pool/pool.go, internal/pool/pool_test.go
=> Do not create new items if index is full

.github/workflows/tests.yml, CHANGELOG.md, internal/query/result_range_test.go, internal/query/result_set_range_test.go, internal/xiter/xiter.go, internal/xiter/xiter_experiment_go1.23.go, query/example_test.go, query/result.go, tests/integration/query_range_test.go
=> fixed build tags for range-over

CHANGELOG.md, example_test.go, internal/query/client.go, internal/query/execute_query.go, internal/query/options/execute.go, internal/query/options/retry.go, internal/query/session.go, internal/query/transaction.go, internal/query/transaction_test.go, query/example_test.go, tests/integration/query_execute_test.go, tests/integration/query_multi_result_sets_test.go, tests/integration/query_range_test.go, tests/integration/query_read_row_test.go
=> make option `query.WithIdempotent()` as option for `query.Client.{Exec,Query,QueryResultSet,QueryRow}`

operation/client.go, operation/example_test.go, operation/kind.go, tests/integration/operation_test.go
=> added type `operation.kind` for `operation.Client.List` method

internal/pool/errors.go, internal/pool/pool.go, internal/pool/pool_test.go
=> refactoring of internal/pool

CHANGELOG.md, log/topic.go
=> Fixed log messages for send nessage to topic

CHANGELOG.md, internal/grpcwrapper/rawtopic/rawtopicwriter/messages.go, log/topic.go, trace/topic.go, trace/topic_gtrace.go
=> Added write topic writer ack

CHANGELOG.md, internal/operation/metadata/metadata.go, internal/query/client.go, internal/query/options/execute_script.go, operation/client.go, operation/example_test.go, operation/kind.go, tests/integration/operation_test.go
=> splitted `operation.List` to five list operations `operation.List{BuildIndex,ImportFromS3,ExportToS3,ExportToYT,ExecuteQuery}`

tests/slo/Dockerfile
=> Update golang version to 1.23 in SLO Dockerfile

CHANGELOG.md, internal/query/client.go, internal/query/config/config.go
=> * Enabled by default usage of `internal/pool` in `internal/query.Client`

.github/workflows/lint.yml, tests/integration/database_sql_get_column_type_test.go, tests/integration/database_sql_get_columns_test.go, tests/integration/database_sql_get_index_columns_test.go, tests/integration/database_sql_get_indexes_test.go, tests/integration/database_sql_get_primary_keys_test.go, tests/integration/database_sql_get_tables_test.go, tests/integration/database_sql_is_column_exists_test.go, tests/integration/database_sql_is_primary_key_test.go, tests/integration/database_sql_is_table_exists_test.go
=> update gofumpt in CI for use samve version as golangcilint

CHANGELOG.md, internal/topic/topicwriterinternal/writer_reconnector.go, internal/topic/topicwriterinternal/writer_reconnector_test.go, topic/topicwriter/topicwriter.go
=> special error for detect about written messages can be delivered to the server when write error happened.

CHANGELOG.md, driver.go, query/client.go
=> * Removed `experimantal` comment for query service client

topic/topicwriter/topicwriter_test.go
=> fixed example typo

CHANGELOG.md, metrics/driver.go, metrics/table.go
=> Fix tracing details check for some metrics

tests/slo/internal/workers/read.go, tests/slo/internal/workers/write.go
=> fixed last error messages

internal/table/client.go
=> refactoring of internal/table.Client.CreateSession retryer usage

CHANGELOG.md, internal/query/scanner/struct.go, internal/query/scanner/struct_test.go
=> Allowed skip struct field in ScanStruct by tag -

CHANGELOG.md, metrics/query.go
=> Do not report latency metrics when metrics are disabled

CHANGELOG.md, metrics/query.go
=> Do not report `query_session_count` metrics when metrics are disabled

options.go
=> marked as deprecated options WithDatabase and WithEndpoint

tests/integration/database_sql_regression_test.go
=> add database uuid tests

CHANGELOG.md, spans/retry.go, spans/traces.go
=> * Added `spans.Retry` constructor of `trace.Retry`

CHANGELOG.md, internal/query/execute_query.go, internal/query/options/execute.go, internal/query/options/execute_test.go, query/execute_options.go
=> * Renamed `query.WithPoolID()` into `query.WithResourcePool()`

CHANGELOG.md, internal/table/scanner/scanner.go
=> add scan to uuid

CHANGELOG.md, internal/params/dict.go, internal/params/dict_test.go, internal/params/list.go, internal/params/list_test.go, internal/params/optional.go, internal/params/optional_test.go, internal/params/parameters.go, internal/params/set.go, internal/params/set_test.go, internal/params/struct.go, internal/params/struct_test.go, internal/params/tuple.go, internal/params/tuple_test.go, internal/params/variant_struct.go, internal/params/variant_struct_test.go, internal/params/variant_tuple.go, internal/params/variant_tuple_test.go
=> uuid-fix-break

CHANGELOG.md, driver.go, options.go
=> Fix nil pointer dereference in meta balancer initialization

CHANGELOG.md, spans/driver.go, spans/driver_test.go, spans/spans.go
=> Small broken change: Fixed `traceparent` header for tracing grpc requests + * Added method `ID()` into `spans.Span` interface

CHANGELOG.md, internal/balancer/balancer.go
=> Use `pick_first` balancer for discovery attempts

internal/balancer/balancer.go
=> Removed balancer.OnUpdate

internal/topic/topicreadercommon/committer.go
=> improove error text

CHANGELOG.md, example_test.go, params_map.go
=> Added experimental ydb.ParamsFromMap and ydb.MustParamsFromMap for build query parameters

CHANGELOG.md, internal/credentials/access_error.go, internal/xerrors/operation.go, sugar/dsn.go, sugar/dsn_test.go, tests/integration/driver_test.go
=> `sugar.DSN` refactoring + added test for static credentials

CHANGELOG.md, examples/go.mod, examples/go.sum, go.mod, go.sum, internal/grpcwrapper/rawtopic/controlplane_types.go, internal/table/session.go, table/options/models.go, table/options/options.go, tests/slo/go.mod, tests/slo/go.sum
Added option to get shard nodeId for describe table call
- [ x ] Feature
=> Added option to get shard nodeId for describe table call

.github/workflows/tests.yml, tests/integration/table_scan_error_test.go
=> enable_antlr4_parser in experiment tests

CHANGELOG.md, options.go, tests/integration/driver_test.go
=> Added WithStaticCredentialsLogin+WithStaticCredentialsPassword

CHANGELOG.md, internal/params/builder.go, internal/params/builder_test.go, internal/params/dict_test.go, internal/params/list_test.go, internal/params/optional_test.go, internal/params/parameters.go, internal/params/parameters_test.go, internal/params/pg_test.go, internal/params/set_test.go, internal/params/struct_test.go, internal/params/tuple_test.go, internal/params/variant_struct_test.go, internal/params/variant_tuple_test.go, internal/types/types.go, internal/types/types_test.go, internal/value/value.go, internal/value/value_test.go, params_builder_test.go
=> * Supported raw protobuf typed value using `ydb.ParamsBuilder()`

CHANGELOG.md, driver.go, internal/query/client.go, internal/query/errors.go, tests/integration/driver_test.go
=> fixed bug with multiple closing driver

README.md
=> [1589] fix readme

tests/integration/driver_test.go
=> fixed test with drop user on nightly ydb

topic/topicreader/reader.go
=> improve comments

CHANGELOG.md, internal/value/value.go, internal/value/value_test.go, tests/integration/sugar_unmarhall_result_set_test.go
=> Supported of list, set and struct for unmarshall using `sugar.Unmarshall...`

CHANGELOG.md, internal/credentials/errors.go, internal/credentials/errors_test.go, internal/credentials/static.go
=> fixed issue 'Explicit null dereferenced' (CWE-476)

CHANGELOG.md, internal/balancer/balancer.go, internal/topic/topicwriterinternal/writer_reconnector.go, log/topic.go, trace/topic.go, trace/topic_gtrace.go
=> no endpoints retriable error now

internal/xsync/slice.go, internal/xsync/slice_test.go
=> added `xsync.Slice`

CHANGELOG.md, internal/query/session_core.go, internal/table/retry_test.go, internal/table/session.go, internal/xsql/connector.go, internal/xsql/errors.go, tests/integration/basic_example_database_sql_test.go
=> check context before call session close

CHANGELOG.md, internal/topic/topicreadercommon/message.go, internal/topic/topicreadercommon/message_content_pool_test.go, internal/topic/topicreadercommon/one_time_reader.go, internal/topic/topicreadercommon/one_time_reader_test.go
=> Prevented create decoder instance until start read a message from topics

CHANGELOG.md, log/topic.go
Topic logs for methods serving a single query do not inherit fields for context passed to this method
Added request context fields to topic log instances
=> Pass context to topic event logs where available

CHANGELOG.md, internal/table/session.go
=> * Fixed deadlock on closing table session with internal query session core

CHANGELOG.md, internal/query/result.go
=> check stats exists before callback stat within newResult

internal/topic/topiclistenerinternal/stream_listener.go
=> remove no need nil check

internal/balancer/balancer.go, internal/conn/conn.go
=> supress continueslu linter warnings

CHANGELOG.md, table/options/models.go, tests/integration/table_create_table_description_test.go
=> Added virtualtimestamps field to cdc description

CHANGELOG.md, internal/query/row.go, internal/query/row_test.go
=> * Added stacktrace call to row scan errors for detect broken client code

internal/query/session_core.go
=> Added debug mark for attach sessions

.github/workflows/breaking.yml, .github/workflows/check-codegen.yml, .github/workflows/examples.yml, .github/workflows/lint.yml, .github/workflows/slo.yml, .github/workflows/tests.yml
=> added go1.24 to CI

CHANGELOG.md, internal/pool/pool.go, internal/pool/pool_test.go, internal/query/client_test.go, internal/table/retry_test.go
=> Pool error handling

internal/query/session_core.go
=> refactoring of attach stream goroutine label

.gitignore, CHANGELOG.md, internal/table/session.go, table/options/models.go
Added `StoreType` [field](https://github.com/ydb-platform/ydb-api-protos/blame/master/protos/ydb_table.proto#L766) from `DescribeTableResult` to `options.Description`.
=> Added StoreType to table description

log/driver.go
=> small changes in logs

CHANGELOG.md, internal/xcontext/done.go, internal/xcontext/done_test.go
=> * Fixed bug in `internal/xcontext.WithDone` (not listening chan done)

internal/xcontext/done.go, internal/xcontext/done_test.go
=> Reverted implementation of internal/xcontext.WithDone

CHANGELOG.md, internal/conn/conn.go
=> * Fixed bug with concurrent rewrites source slice of `grpc.DialOption` on dial step

tests/integration/database_sql_metrics_test.go, tests/integration/helpers_test.go
=> fixed cleanup for database/sql driver

internal/xtest/leak.go, internal/xtest/leak_test.go, tests/integration/basic_example_database_sql_bindings_test.go, tests/integration/basic_example_database_sql_test.go, tests/integration/helpers_test.go
=> added internal/xtest.CheckGoroutinesLeak

CHANGELOG.md, examples/read_table/main.go, internal/table/client.go, internal/table/session.go, table/table.go, tests/integration/kv_test.go
Add ReadRows method to the table.Client, because it doesn't really use session, but sessions sometimes override PreferredNodeID.
=> Add ReadRows to the table.Client

config/defaults.go, driver_string_test.go, internal/config/defaults.go
=> move default constants fo internal,  mark them deprecated

CHANGELOG.md, metrics/driver.go
Issue Number: #1615
Add a new metric ydb_go_sdk_ydb_info with the current version of the SDK
=> Add a new metric ydb_go_sdk_ydb_info with the current version of the SDK

CHANGELOG.md, internal/query/session_core.go, internal/query/session_core_test.go
=> * Fixed panic on closing `internal/query/sessionCore.done` channel twice

CHANGELOG.md, params_builder.go, params_map.go
=> * Removed comment `experimental` from `ydb.ParamsBuilder` and `ydb.ParamsFromMap`

CHANGELOG.md, query/transaction.go
=> * Added `query.TransactionActor` type alias to `query.TxActor` for compatibility with `table.Client` API's

CHANGELOG.md, internal/params/parameters.go, internal/types/types.go, internal/value/time.go, internal/value/value.go, internal/value/value_test.go, tests/integration/query_execute_test.go
=> * Supported wide `Date32`, `Datetime64` and `Timestamp64` types

CHANGELOG.md, internal/params/parameters.go, internal/types/types.go, internal/value/time.go, internal/value/value.go, tests/integration/query_execute_test.go
=> * Supported wide `Interval64` type

CHANGELOG.md, internal/query/client.go, internal/query/client_test.go, internal/query/execute_query.go, internal/query/options/execute.go, internal/query/options/retry.go, internal/query/session.go, internal/query/transaction.go, metrics/query.go, query/client.go, trace/query.go, trace/query_gtrace.go
Added export of advanced metric information for QueryService calls
-
-
-
=> metric-export-extended-info-with-labels

CHANGELOG.md, dsn.go, dsn_test.go, internal/bind/bind.go, internal/bind/errors.go, internal/bind/wide_time_types.go, internal/bind/wide_time_types_test.go, internal/xsql/options.go, params_map.go, params_test.go, query_bind_test.go, sql.go
=> * Added bindings elipsis into `ydb.ParamsFromMap` for bind wide time types

CHANGELOG.md, table/table.go
=> * Changed argument types in `table.Client.ReadRows` to public types for compatibility with mock-generation

CHANGELOG.md, internal/pool/pool.go, internal/pool/pool_test.go, metrics/query.go
=> * Added query client session pool metrics: create_in_progress, in_use, waiters_queue + Added pool item closing for not-alived item

.github/workflows/tests.yml, tests/integration/query_execute_test.go
=> added 24.4 and 25.1 ydb versions to integration tests

tests/integration/tx_test.go
=> Added TestInteractiveTx test

internal/query/row_test.go, internal/table/scanner/perfomance_test.go, internal/table/scanner/scanner_data_test.go
```
BenchmarkScanner/Scan-12         	 3562569	       338.3 ns/op	     247 B/op	      11 allocs/op
BenchmarkScanner/ScanNamed-12    	 2980160	       414.6 ns/op	     343 B/op	      14 allocs/op
BenchmarkScanner/ScanStruct-12   	 1816064	       677.1 ns/op	     351 B/op	      17 allocs/op
PASS
```
-
-
-
=> added benchmarks for Scan, ScanNamed, ScanStruct

CHANGELOG.md, internal/topic/topicreadercommon/committer.go
=> Ignore delay before sync commit

.github/workflows/tests.yml
=> show ydb server version before start tests

CHANGELOG.md, internal/topic/topiclistenerinternal/stream_listener.go, internal/topic/topicreadercommon/init_message.go, internal/topic/topicreaderinternal/stream_reader_impl.go, topic/topicoptions/topicoptions_reader.go
=> add flag for disable split-merge support

internal/balancer/balancer.go
=> refactoring of internal/balancer logic: delete unnesesary call meta context, renamed internal funcs for better understanding of balancer internals

examples/go.mod, examples/go.sum, go.mod, go.sum, internal/repeater/repeater_test.go, internal/topic/topicreadercommon/committer_test.go, internal/xtest/clock.go, tests/slo/go.mod, tests/slo/go.sum
Clockwork 0.3.0 version was used
Update clockwork version to 0.0.5 and fix FastClock according to the new API from clockwork for tests
=> Update clockwork version

internal/value/value.go, internal/value/value_test.go
=> Fix decimal yql slice bounds out of range

internal/value/value.go, internal/value/value_test.go
=> Fix handling of zero values for DyNumber

.github/workflows/tests.yml, tests/integration/query_execute_test.go
=> Added latest tag to integration tests matrix

CHANGELOG.md, internal/topic/topicreaderinternal/stream_reader_impl.go, tests/integration/topic_transactions_test.go
=> Fixed fail topic reader on TLI

.github/workflows/lint.yml
Workaround incompatible old golang-lint-ci and go1.24
=> set fixed golang version

internal/query/session_core.go
=> Added closing close hint check

CHANGELOG.md, internal/xerrors/issues.go, internal/xerrors/issues_test.go, internal/xerrors/operation.go, internal/xerrors/operation_test.go, retry/errors_data_test.go
=> * Marked as non-retryable operation error `ABORTED` with internal issue `200509` ("Datashard program size limit exceeded")

internal/balancer/balancer_test.go
If there are issues with IP addresses via DNS, YDB startup gets stuck.
The problem was fixed early, but no tests exist.
Unit test for guaranteed stability.
=> Failover unit test for DNS with unavailable IP addresses

CHANGELOG.md, pkg/xerrors/stacktrace.go
=> Fix stack depth

CHANGELOG.md, internal/config/defaults.go
=> Fixed grpc default message size limit

CHANGELOG.md, internal/topic/topicreaderinternal/stream_reader_impl.go
=> Bugfix: error handling in internaltopicreader.addOnTransactionCompletedHandler is invalid
